### ISSUE TITLE
send text message not working

### ISSUE THREAD

**Issue by alijundi** [allburov/whatsapp-http-api#11]
I receive the below:

```
WhatsApp HTTP API is running on: http://[::1]:3000
[Nest] 28   - 12/11/2021, 9:55:14 AM   [ExceptionsHandler] Evaluation failed: TypeError: Cannot read property 'default' of undefined
    at __puppeteer_evaluation_script__:3:48 +53459ms
Error: Evaluation failed: TypeError: Cannot read property 'default' of undefined
    at __puppeteer_evaluation_script__:3:48
    at ExecutionContext._evaluateInternal (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[Nest] 28   - 12/11/2021, 9:55:28 AM   [ExceptionsHandler] Evaluation failed: TypeError: Cannot read property 'attributes' of undefined
    at Object.window.WAPI.window.WAPI.getHost (/app/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:55001)
    at __puppeteer_evaluation_script__:1:28 +14195ms
Error: Evaluation failed: TypeError: Cannot read property 'attributes' of undefined
    at Object.window.WAPI.window.WAPI.getHost (/app/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:55001)
    at __puppeteer_evaluation_script__:1:28
    at ExecutionContext._evaluateInternal (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:28) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'sendChatStateComposing' of undefined
    at Object.window.WAPI.window.WAPI.startTyping (/app/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:42456)
    at __puppeteer_evaluation_script__:3:37
    at ExecutionContext._evaluateInternal (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:28) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:28) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:28) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'get' of undefined
    at Object.window.WAPI.window.WAPI.sendMessage (/app/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:35932)
    at __puppeteer_evaluation_script__:3:53
    at ExecutionContext._evaluateInternal (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:28) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

**Comment by alijundi** [comment]
@allburov how can I update the venom part of the docker app? Can you please let me know. I think it is related to old venom part

Thank you.

**Comment by allburov** [comment]
@alijundi hi! Have a look at the project https://github.com/diazzaid/whatsapp-api-venom

It has almost the latest venom. If it doesn't - at least it'll be easy to upgrate venom part there

**Comment by alijundi** [comment]
Done
