### ISSUE TITLE
get/api/messages random error

### ISSUE THREAD

**Issue by liamgwallace** [allburov/whatsapp-http-api#120]
I am trying to get historical messages from chats using get/api/messages but keep getting an error. Also randomly it works sometimes. This is the same for single person messages and group messages.

What am i doing wrong here?

**Curl**
curl -X 'GET' \
  'http://localhost:3000/api/messages?chatId=447746320420%40c.us&limit=10&session=default' \
  -H 'accept: application/json'
  
  **Request URL**
http://localhost:3000/api/messages?chatId=447746320420%40c.us&limit=10&session=default

Code	Details
500
Undocumented
Error: Internal Server Error

**Response body**
{
  "statusCode": 500,
  "timestamp": "2023-06-19T14:38:09.304Z",
  "exception": {
    "stack": "TypeError: Cannot read properties of undefined (reading 'save')\n    at WhatsappSessionWebJSCore.downloadMedia (/app/dist/core/session.webjs.core.js:261:47)\n    at WhatsappSessionWebJSCore.processIncomingMessage (/app/dist/core/session.webjs.core.js:235:21)\n    at WhatsappSessionWebJSCore.getMessages (/app/dist/core/session.webjs.core.js:113:36)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async /app/node_modules/@nestjs/core/router/router-execution-context.js:46:28\n    at async /app/node_modules/@nestjs/core/router/router-proxy.js:9:17",
    "message": "Cannot read properties of undefined (reading 'save')",
    "name": "TypeError"
  },
  "request": {
    "path": "/api/messages?chatId=447746320420%40c.us&limit=10&session=default",
    "method": "GET",
    "body": {},
    "query": {
      "chatId": "447746320420@c.us",
      "limit": "10",
      "session": "default"
    }
  },
  "version": {
    "version": "2023.6.1",
    "tier": "CORE",
    "browser": "/usr/bin/chromium"
  }
}
Response headers
 connection: keep-alive 
 content-length: 1018 
 content-type: application/json; charset=utf-8 
 date: Mon,19 Jun 2023 14:38:09 GMT 
 etag: W/"3fa-DqjF66rIMyFPqawdLh7qwjvDoUs" 
 keep-alive: timeout=5 
 x-powered-by: Express

**Comment by aUntitledProject** [comment]
+1
Have the same issue on the newest version of Waha core. (WEBJS){
  "statusCode": 500,
  "timestamp": "2026-04-18T17:04:39.913Z",
  "exception": {
    "message": "t",
    "name": "t",
    "stack": "t: t\n    at #evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:391:56)\n    at async ExecutionContext.evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:277:16)\n    at async IsolatedWorld.evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/IsolatedWorld.js:100:16)\n    at async CdpFrame.evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Frame.js:362:20)\n    at async CdpPage.evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Page.js:818:20)\n    at async WPage.evaluate (/app/dist/core/engines/webjs/WPage.js:13:20)\n    at async WebjsClientCore.getChatById (/app/node_modules/whatsapp-web.js/src/Client.js:1171:22)\n    at async WhatsappSessionWebJSCore.getChatMessages (/app/dist/core/engines/webjs/session.webjs.core.js:595:9)"
  },
  "request": {
    "path": "/api/default/chats/PHONENUMBER_HEREc.us/messages?sortBy=timestamp&sortOrder=desc&downloadMedia=true&merge=true&limit=10&offset=1",
    "method": "GET",
    "query": {
      "sortBy": "timestamp",
      "sortOrder": "desc",
      "downloadMedia": "true",
      "merge": "true",
      "limit": "10",
      "offset": "1"
    }
  },
  "version": {
    "version": "2026.4.2",
    "engine": "WEBJS",
    "tier": "CORE",
    "browser": "/usr/bin/chromium",
    "platform": "linux/x64",
    "worker": {
      "id": null
    }
  }
}
