### ISSUE TITLE
Adding to a group now fails with the latest version

### ISSUE THREAD

**Issue by Gaspa79** [allburov/whatsapp-http-api#161]
Using version  `"version": "2023.8.8",`

Now adding a whatsapp number to a group the same way as before either returns a "200" but does nothing, or returns a 500: 

`{
  "statusCode": 500,
  "timestamp": "2023-08-09T19:31:04.914Z",
  "exception": {
    "stack": "Error: Evaluation failed: i\n    at ExecutionContext._evaluateInternal (/app/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ExecutionContext.evaluate (/app/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)\n    at async GroupChat.addParticipants (/app/node_modules/whatsapp-web.js/src/structures/GroupChat.js:62:16)\n    at async /app/node_modules/@nestjs/core/router/router-execution-context.js:46:28\n    at async /app/node_modules/@nestjs/core/router/router-proxy.js:9:17",
    "message": "Evaluation failed: i",
    "name": "Error"
  },
  "request": {
    "path": "/api/default/groups/120363026XXXXXXXXXXX%40g.us/participants/add",
    "method": "POST",
    "body": {
      "participants": [
        {
          "id": "29940XXXXX@c.us"
        }
      ]
    },
    "query": {}
  },`

Of course I'm checking that the contact is correct beforehand by checking that it exists. Any ideas what this could be? Maybe I'm missing something that I wasn't missing before, but it used to work perfectly with the version from two months ago

**Comment by allburov** [comment]
Hi! Waiting for engine to support it, some changes have been made in WhatsApp itself. https://github.com/pedroslopez/whatsapp-web.js/pull/2344

As a quick fix - we'd suggest to send invite code (link) to the contact https://waha.devlike.pro/docs/how-to/groups/#invite-code so they can accept group invitation
