### ISSUE TITLE
Error 500 When Sending Messages via API on Plus Version - Cannot Read 'WidFactory' Properties

### ISSUE THREAD

**Issue by rathoreprashant** [allburov/whatsapp-http-api#204]
### Steps to Reproduce:

Make a POST request to the API endpoint with the following request body:

```
curl -X 'POST' \
  'http://139.84.132.92:3000/api/sendText' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
    "chatId": "7225870407",
    "text": "Hi there!",
    "session": "neww01"
  }'

```
### Expected Behavior:

The API should successfully send the message to the specified chat session.

### Actual Behavior:

The API returns a 500 Internal Server Error with the following response:

```
{
  "statusCode": 500,
  "timestamp": "2023-09-12T04:55:55.250Z",
  "exception": {
    "stack": "Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'WidFactory')\n    at __puppeteer_evaluation_script__:2:42\n    at ExecutionContext._evaluateInternal (/app/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ExecutionContext.evaluate (/app/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)\n    at async Client.sendMessage (/app/node_modules/whatsapp-web.js/src/Client.js:869:28)\n    at async /app/node_modules/@nestjs/core/router/router-execution-context.js:46:28\n    at async /app/node_modules/@nestjs/core/router/router-proxy.js:9:17",
    "message": "Evaluation failed: TypeError: Cannot read properties of undefined (reading 'WidFactory')\n    at __puppeteer_evaluation_script__:2:42",
    "name": "Error"
  },
  "request": {
    "path": "/api/sendText",
    "method": "POST",
    "body": {
      "chatId": "7225870406",
      "text": "Hi there!",
      "session": "neww01"
    },
    "query": {}
  },
  "version": {
    "version": "2023.9.3",
    "tier": "PLUS",
    "browser": "/usr/bin/chromium"
  }
}
```

### Additional Information:

I am able to create multiple sessions successfully, but I encounter the above error when attempting to send a message through the API.
Please assist in resolving this issue and provide guidance on how to fix it.

**Comment by allburov** [comment]
Could you show statuses for the session from `GET /api/sessions/` endpoint? It's probably still "SCAN_QR"?

**Comment by allburov** [comment]
Could you try to use the latest version `2023.9.7`?
