### ISSUE TITLE
[BUG][WEBJS] - Internal server error - ProtocolError: Protocol error (Runtime.callFunctionOn)

### ISSUE THREAD

**Issue by ehussain** [allburov/whatsapp-http-api#244]
**Describe the bug**

Sending a message to a number caused a random exception.

**Version**

```json
{
  "version": "2023.12.2",
  "engine": "WEBJS",
  "tier": "PLUS",
  "browser": "/usr/bin/chromium"
}
```

**To Reproduce** Steps to reproduce the behavior:

```
POST: /api/sendText

{"chatId":"9725470XXXXX@c.us","session":"XXXXX","type":"text","text":"\u05d1\u05d5\u05e7\u05e8 \u05d8\u05d5\u05d1 \u05d1\u05ea \u05d0\u05dc , \u05d6\u05d5 \u05dc\u05d9\u05de\u05d5\u05e8 \n\u05d4\u05e4\u05d5\u05dc\u05d9\u05e1\u05d4 \u05d4\u05e0\"\u05dc \u05d1\u05db\u05dc\u05dc \u05dc\u05d0 \u05e0\u05de\u05e6\u05d0\u05ea \u05ea\u05d7\u05ea \u05d8\u05d9\u05e4\u05d5\u05dc\u05e0\u05d5 \u05d5\u05d0\u05e0\u05d9 \u05dc\u05d0 \u05d9\u05db\u05d5\u05dc\u05d4 \u05dc\u05d1\u05d3\u05d5\u05e7 \u05d1\u05de\u05d4 \u05de\u05d3\u05d5\u05d1\u05e8 \n\u05e0\u05d9\u05ea\u05df \u05dc\u05d1\u05d3\u05d5\u05e7 \u05de\u05d5\u05dc \u05e9\u05d9\u05e8\u05d5\u05ea \u05dc\u05e7\u05d5\u05d7\u05d5\u05ea \u05e9\u05dc \u05db\u05dc\u05dc .\n\u05d0\u05dd \u05ea\u05e8\u05e6\u05d9 \u05d0\u05ea \u05e2\u05d6\u05e8\u05ea\u05d9 \u05d1\u05e9\u05d9\u05d7\u05d4 \u05de\u05d5\u05dc\u05dd \u05dc\u05d1\u05d3\u05d9\u05e7\u05d4 \u05e2\u05d3\u05db\u05e0\u05d9 \u05d0\u05d5\u05ea\u05d9"}

```

```
{"statusCode":500,"timestamp":"2023-12-17T09:34:58.349Z","exception":{"stack":"ProtocolError: Protocol error (Runtime.callFunctionOn): Promise was collected\n    at /app/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:230:24\n    at new Promise (<anonymous>)\n    at CDPSession.send (/app/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:226:16)\n    at ExecutionContext._evaluateInternal (/app/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:204:50)\n    at ExecutionContext.evaluate (/app/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:27)\n    at DOMWorld.evaluate (/app/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:97:24)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","name":"ProtocolError","originalMessage":"Promise was collected","message":"Protocol error (Runtime.callFunctionOn): Promise was collected"},"request":{"path":"/api/sendText","method":"POST","body":{"chatId":"972547XXXXX@c.us","session":"XXXXX","type":"text","text":"בוקר טוב בת אל , זו לימור \nהפוליסה הנ\"ל בכלל לא נמצאת תחת טיפולנו ואני לא יכולה לבדוק במה מדובר \nניתן לבדוק מול שירות לקוחות של כלל .\nאם תרצי את עזרתי בשיחה מולם לבדיקה עדכני אותי"},"query":{}},"version":{"version":"2023.12.2","engine":"WEBJS","tier":"PLUS","browser":"/usr/bin/chromium"}}
```

**Expected behavior**

Message Should be sent successfully. Instead it gives exception.

**Engine** I'm using **WEBJS** engine.

**Comment by adolfoflores** [comment]
+1

**Comment by whera** [comment]
+1

**Comment by YosefAdPro** [comment]
+1

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Hi! 
We've updated chrome and puppeter in `2025.4.2` and added a global error handler for some common issues (it'll restart browser if it get any errors like ProtocolError)

It won't fix all such errors, but should reduce the amount a lot.

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
