### ISSUE TITLE
[BUG][NOWEB] -  Get error response when invite to group

### ISSUE THREAD

**Issue by bobykurniawan11** [allburov/whatsapp-http-api#266]
``` 
curl --location 'https://xxxxxxxx/api/3c28a166-67bd-46df-9309-211eea3b51ae/groups/12036xxxxxxxxx@g.us/participants/add' \
--header 'X-Api-Key: xxxxxx' \
--header 'Content-Type: application/json' \
--data-raw '{
  "participants": [
    {
      "id": "+xxxxxxxxx@c.us"
    }
  ]
}
```

I get this response

```
{
    "statusCode": 500,
    "timestamp": "2024-02-28T05:37:51.862Z",
    "exception": {
        "stack": "Error: bad-request\n    at assertNodeErrorFree (/app/node_modules/@adiwajshing/baileys/lib/WABinary/generic-utils.js:56:15)\n    at query (/app/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:140:48)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Object.groupParticipantsUpdate (/app/node_modules/@adiwajshing/baileys/lib/Socket/groups.js:142:28)\n    at async /app/node_modules/@nestjs/core/router/router-execution-context.js:46:28\n    at async /app/node_modules/@nestjs/core/router/router-proxy.js:9:17",
        "message": "bad-request",
        "data": 400,
        "isBoom": true,
        "isServer": true,
        "output": {},
        "name": "Error"
    },
    "request": {
        "path": "/api/8868b306-7cfc-42ce-9c85-02f84e73141a/groups/120363201775966066@g.us/participants/add",
        "method": "POST",
        "body": {
            "participants": [
                {
                    "id": "6289670036650@c.us"
                }
            ]
        },
        "query": {}
    },
    "version": {
        "version": "2023.12.3",
        "engine": "NOWEB",
        "tier": "PLUS",
        "browser": "/usr/bin/chromium"
    }
}
```

**Comment by devlikepro** [comment]
Hi! How did you solve the issue? @bobykurniawan11 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
