### ISSUE TITLE
[BUG][WEBJS][CHROME] - Exception when sending a message.

### ISSUE THREAD

**Issue by ehussain** [allburov/whatsapp-http-api#342]
**Describe the bug**
We are facing exception when we try to send a message. This exception is intermittent but very frequent.

**Version**

```json
{"version":"2024.5.8","engine":"WEBJS","tier":"PLUS","browser":"/usr/bin/google-chrome-stable"}
```

**Requests - Responses**

```
{"statusCode":500,"timestamp":"2024-05-22T08:03:51.298Z","exception":{"stack":"Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'unsafe')\n    at window.WWebJS.sendMessage (pptr://__puppeteer_evaluation_script__:38:67)\n    at pptr://__puppeteer_evaluation_script__:10:45\n    at ExecutionContext._ExecutionContext_evaluate (/app/node_modules/whatsapp-web.js/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:229:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ExecutionContext.evaluate (/app/node_modules/whatsapp-web.js/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)\n    at async Client.sendMessage (/app/node_modules/whatsapp-web.js/src/Client.js:945:28)\n    at async /app/node_modules/@nestjs/core/router/router-execution-context.js:46:28\n    at async /app/node_modules/@nestjs/core/router/router-proxy.js:9:17","message":"Evaluation failed: TypeError: Cannot read properties of undefined (reading 'unsafe')\n    at window.WWebJS.sendMessage (pptr://__puppeteer_evaluation_script__:38:67)\n    at pptr://__puppeteer_evaluation_script__:10:45","name":"Error"},"request":{"path":"/api/reply","method":"POST","body":{"chatId":"972522XXXX@c.us","session":"60302","type":"text","text":"בוקר טוב \nטרם חלפו כ- 90 ימי עסקים \nאנו כמובן מלווים את התהליך עד להעברת הסכום לחשבונך","reply_to":"true_972522XXXX@c.us_3EB0376C8C7E2EA03FE54C"},"query":{}},"version":{"version":"2024.5.8","engine":"WEBJS","tier":"PLUS","browser":"/usr/bin/google-chrome-stable"}}
```

[![patron:ADVANCED](https://img.shields.io/badge/patron-ADVANCED-4cd07d)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by allburov** [comment]
LEt's try `2024.5.9` and see how it goes!

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Did you see the issue again? @ehussain 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by ehussain** [comment]
Not in past couple of days. May be we can wait for few more days to find out if it is still happening.

[![patron:ADVANCED](https://img.shields.io/badge/patron-ADVANCED-4cd07d)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
How is it going?

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
