### ISSUE TITLE
[BUG][NOWEB] - Send Status to 10K+ contacts -  500 error when sending status stories to a large number of contacts

### ISSUE THREAD

**Issue by sg957** [allburov/whatsapp-http-api#413]
**I'm getting a 500 error when sending status stories to a large number of contacts
Error description**

message:500 - "{\"statusCode\":500,\"timestamp\":\"2024-07-01T23:56:06.826Z\",\"exception\":{\"stack\":\"RangeError [ERR_OUT_OF_RANGE]: The value of \\\"value\\\" is out of range. It must be >= 0 and <= 255. Received 294\\n    at writeU_Int8 (node:internal/buffer:740:11)\\n    at Buffer.writeUInt8 (node:internal/buffer:750:10)\\n    at Object.encodeFrame (/app/node_modules/[@adiwajshing](https://t.me/adiwajshing)/baileys/lib/Utils/noise-handler.js:123:19)\\n    at sendRawMessage (/app/node_modules/[@adiwajshing](https://t.me/adiwajshing)/baileys/lib/Socket/socket.js:61:29)\\n    at sendNode (/app/node_modules/[@adiwajshing](https://t.me/adiwajshing)/baileys/lib/Socket/socket.js:79:16)\\n    at /app/node_modules/[@adiwajshing](https://t.me/adiwajshing)/baileys/lib/Socket/messages-send.js:442:19\\n    at async Object.transaction (/app/node_modules/[@adiwajshing](https://t.me/adiwajshing)/baileys/lib/Utils/auth-utils.js:136:26)\\n    at async relayMessage (/app/node_modules/[@adiwajshing](https://t.me/adiwajshing)/baileys/lib/Socket/messages-send.js:280:9)\\n    at async Object.sendMessage (/app/node_modules/[@adiwajshing](https://t.me/adiwajshing)/baileys/lib/Socket/messages-send.js:654:17)\",\"code\":\"ERR_OUT_OF_RANGE\",\"message\":\"The value of \\\"value\\\" is out of range. It must be >= 0 and <= 255. Received
tack:AxiosError: Request failed with status code 500\n    at settle (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/settle.js:19:12)\n    at RedirectableRequest.handleResponse (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/adapters/http.js:537:9)\n    at RedirectableRequest.emit (node:events:531:35)\n    at RedirectableRequest.emit (node:domain:488:12)\n    at RedirectableRequest._processResponse (/usr/local/lib/node_modules/n8n/node_modules/follow-redirects/index.js:398:10)\n    at ClientRequest.RedirectableRequest._onNativeResponse (/usr/local/lib/node_modules/n8n/node_modules/follow-redirects/index.js:91:12)\n    at Object.onceWrapper (node:events:634:26)\n    at ClientRequest.emit (node:events:519:28)\n    at ClientRequest.emit (node:domain:488:12)\n    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:698:27)\n    at Axios.request (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/Axios.js:45:41)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at requestFn (/usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/NodeExecuteFunctions.js:567:33)\n    at proxyRequestToAxios (/usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/NodeExecuteFunctions.js:570:26)\n    at Object.request (/usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/NodeExecuteFunctions.js:1992:50) 
code:ERR_BAD_RESPONSE 
status:500

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Related https://github.com/devlikeapro/waha/issues/390

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Hi! JFYI - starting **2024.11.1** version you can send status (aka stories) via WEBJS engine as well, it doesn't have the 3K contacts issues :crossed_fingers: 
https://waha.devlike.pro/docs/how-to/status/#features

It doesn't require `contacts`, it'll send status to all contacts for now 
```bash
POST /api/{session}/status/image
```
```json
{
  "file": {
    "mimetype": "image/jpeg",
    "url": "https://github.com/devlikeapro/waha/raw/core/examples/dev.likeapro.jpg"
  },
  "caption": "string"
}
```

We're working on proper solution for NOWEB as well, no ETA yet tho :( 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Hi! Could you try **2024.11.4** version and give feedback :pray: :crossed_fingers: 

Tested with ~99K contacts, all send.
:information_source: 
1. The first request will take **few minutes** to establish communications (sessions) with all participants
2. The second request will be faster

Because the 1st request requires a lot of time and because we're restarting NOWEB socket every 30 minutes or so - it's possible to send the request between those restarts :( 
So you can call `/api/sessions/{NAME}/restart` right before you'll send the first story to contacts and wait for 10 seconds until it's WORKING and then send it.
Not ideal, we'll work on the better mechanism to detect "in use socket" in future version :+1: 

----

**NOWEB** doesn't require `contacts` list anymore, you can send it as 
```
POST /api/{session}/status/text
```
```json
{
  "text": "Have a look! https://waha.devlike.pro/",
  "backgroundColor": "#38b42f",
  "font": 1
}
```
it'll fetch all contacts available in [NOWEB Store](https://waha.devlike.pro/docs/engines/noweb/#store) - basicly all your phone contacts


[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by TheOneironaut** [comment]
> Hi! Could you try **2024.11.4** version and give feedback 🙏 🤞
> 
> Tested with ~99K contacts, all send. ℹ️
> 
> 1. The first request will take **few minutes** to establish communications (sessions) with all participants
> 2. The second request will be faster
> 
> Because the 1st request requires a lot of time and because we're restarting NOWEB socket every 30 minutes or so - it's possible to send the request between those restarts :( So you can call `/api/sessions/{NAME}/restart` right before you'll send the first story to contacts and wait for 10 seconds until it's WORKING and then send it. Not ideal, we'll work on the better mechanism to detect "in use socket" in future version 👍
> 
> **NOWEB** doesn't require `contacts` list anymore, you can send it as
> 
> ```
> POST /api/{session}/status/text
> ```
> 
> ```json
> {
>   "text": "Have a look! https://waha.devlike.pro/",
>   "backgroundColor": "#38b42f",
>   "font": 1
> }
> ```
> 
> it'll fetch all contacts available in [NOWEB Store](https://waha.devlike.pro/docs/engines/noweb/#store) - basicly all your phone contacts
> 
> [![patron:PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

I have around 17 thousand contacts and it doesn't work for me.
In the tests you did, you also save with the 99 thousand contacts because if you don't save with them it's probably not relevant?

{
 "statusCode": 500,
 "timestamp": "2024-11-11T13:02:57.039Z",
 "exception": 1006,
 "request": {
 "path": "/api/session_52/status/text",
 "method": "POST",
 "body": {
 "text": "a",
 "backgroundColor": "#38b42f",
 "font": 1
 },
 "query": {}
 },
 "version": {
 "version": "2024.11.4",
 "engine": "NOWEB",
 "tier": "PLUS",
 "browser": "/usr/bin/chromium"
 }
}

**Comment by TheOneironaut** [comment]
> Hi! Could you try **2024.11.4** version and give feedback 🙏 🤞
> 
> Tested with ~99K contacts, all send. ℹ️
> 
> 1. The first request will take **few minutes** to establish communications (sessions) with all participants
> 2. The second request will be faster
> 
> Because the 1st request requires a lot of time and because we're restarting NOWEB socket every 30 minutes or so - it's possible to send the request between those restarts :( So you can call `/api/sessions/{NAME}/restart` right before you'll send the first story to contacts and wait for 10 seconds until it's WORKING and then send it. Not ideal, we'll work on the better mechanism to detect "in use socket" in future version 👍
> 
> **NOWEB** doesn't require `contacts` list anymore, you can send it as
> 
> ```
> POST /api/{session}/status/text
> ```
> 
> ```json
> {
>   "text": "Have a look! https://waha.devlike.pro/",
>   "backgroundColor": "#38b42f",
>   "font": 1
> }
> ```
> 
> it'll fetch all contacts available in [NOWEB Store](https://waha.devlike.pro/docs/engines/noweb/#store) - basicly all your phone contacts
> 
> [![patron:PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

I have around 17 thousand contacts and it doesn't work for me.
In the tests you did, you also save with the 99 thousand contacts because if you don't save with them it's probably not relevant?

{
 "statusCode": 500,
 "timestamp": "2024-11-11T13:02:57.039Z",
 "exception": 1006,
 "request": {
 "path": "/api/session_52/status/text",
 "method": "POST",
 "body": {
 "text": "a",
 "backgroundColor": "#38b42f",
 "font": 1
 },
 "query": {}
 },
 "version": {
 "version": "2024.11.4",
 "engine": "NOWEB",
 "tier": "PLUS",
 "browser": "/usr/bin/chromium"
 }
}

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Hi! What is the `error` or it's empty field? Could you check logs in docker container to see the actual error :pray: 

> it's probably not relevant?

It's, the sessions have been established and that was the main issue :( May be it's a new one one more time...

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by TheOneironaut** [comment]
> Hi! What is the `error` or it's empty field? Could you check logs in docker container to see the actual error 🙏
> 
> > it's probably not relevant?
> 
> It's, the sessions have been established and that was the main issue :( May be it's a new one one more time...
> 
> [![patron:PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)



This is the full output from postman:
`{
    "statusCode": 500,
    "timestamp": "2024-11-12T07:35:32.230Z",
    "exception": {
        "stack": "Error: Timed Out\n    at /app/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:147:32",
        "message": "Timed Out",
        "data": {
            "stack": "Error\n    at promiseTimeout (/app/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:142:19)\n    at waitForMessage (/app/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:119:53)\n    at query (/app/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:141:22)\n    at assertSessions (/app/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:204:34)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async /app/node_modules/@adiwajshing/baileys/lib/Utils/batched.js:10:28\n    at async /app/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:376:21\n    at async Object.transaction (/app/node_modules/@adiwajshing/baileys/lib/Utils/auth-utils.js:136:26)\n    at async relayMessage (/app/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:312:9)\n    at async Object.sendMessage (/app/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:698:17)\n    at async WhatsappSessionNoWebPlus.sendTextStatus (/app/dist/core/engines/noweb/session.noweb.core.js:768:16)"
        },
        "isBoom": true,
        "isServer": false,
        "output": {},
        "name": "Error"
    },
    "request": {
        "path": "/api/test/status/text",
        "method": "POST",
        "body": {
            "text": "testttt",
            "backgroundColor": "#38b42f",
            "font": 1
        },
        "query": {}
    },
    "version": {
        "version": "2024.11.4",
        "engine": "NOWEB",
        "tier": "PLUS",
        "browser": "/usr/bin/chromium"
    }
}`

This is the output of the docker. I started according to your recommendation with restart sessions:
`{"level":40,"time":1731396565095,"pid":1,"hostname":"1023699f0d2f","reqId":2010,"session":"test","name":"NowebPersistentStore","msg":"got receipt update for non-existent message. key: '{\"remoteJid\":\"120363052356022041@g.us\",\"id\":\"0EC59FDCE5BAD4785927EB32F423DDE7\",\"fromMe\":true,\"participant\":\"972544454790:36@s.whatsapp.net\"}'"}
{"level":40,"time":1731396607617,"pid":1,"hostname":"1023699f0d2f","reqId":2010,"session":"test","name":"NowebPersistentStore","msg":"got update for non-existent contact. update: '{\"id\":\"972525729968@s.whatsapp.net\",\"notify\":\"דוד\",\"verifiedName\":\"דוד\"}'"}
{"level":30,"time":1731396615027,"pid":1,"hostname":"1023699f0d2f","reqId":2015,"name":"SessionManager","msg":"Stopping session..."}
{"level":30,"time":1731396615028,"pid":1,"hostname":"1023699f0d2f","reqId":2010,"session":"test","name":"WhatsappSession","job":"auto-restart","class":"SinglePeriodicJobRunner","msg":"Job stopped"}
{"level":30,"time":1731396615028,"pid":1,"hostname":"1023699f0d2f","reqId":2010,"session":"test","name":"WhatsappSession","msg":"Saving creds before stopping..."}
{"level":30,"time":1731396615046,"pid":1,"hostname":"1023699f0d2f","reqId":2010,"session":"test","name":"WhatsappSession","msg":"Creds saved"}
{"level":30,"time":1731396615047,"pid":1,"hostname":"1023699f0d2f","reqId":2010,"session":"test","name":"NOWEBEngine","msg":"connection closed"}
{"level":30,"time":1731396615047,"pid":1,"hostname":"1023699f0d2f","reqId":2015,"name":"SessionManager","msg":"Session has been stopped."}
{"level":30,"time":1731396618049,"pid":1,"hostname":"1023699f0d2f","reqId":2015,"name":"SessionManager","msg":"starting session..."}
{"level":30,"time":1731396618052,"pid":1,"hostname":"1023699f0d2f","reqId":2015,"session":"test","name":"Storage","msg":"Files lifetime is 0, files will not be removed"}
{"level":30,"time":1731396618053,"pid":1,"hostname":"1023699f0d2f","reqId":2015,"session":"test","name":"MediaManager","msg":"Only 'mimetype/ignore-all-media' mimetypes will be downloaded for the session"}
{"level":30,"time":1731396618095,"pid":1,"hostname":"1023699f0d2f","reqId":2015,"session":"test","name":"WhatsappSession","job":"auto-restart","class":"SinglePeriodicJobRunner","msg":"Job started with interval 1700000 ms"}
{"level":30,"time":1731396618095,"pid":1,"hostname":"1023699f0d2f","reqId":2015,"session":"test","msg":"Session has been started."}
{"level":30,"time":1731396618096,"pid":1,"hostname":"1023699f0d2f","reqId":2015,"req":{"id":2015,"method":"POST","url":"/api/sessions/test/restart","query":{},"params":{"0":"api/sessions/test/restart"}},"res":{"statusCode":201},"responseTime":3073,"msg":"request completed"}
{"level":30,"time":1731396618396,"pid":1,"hostname":"1023699f0d2f","reqId":2015,"session":"test","name":"NOWEBEngine","browser":["Ubuntu","Chrome","22.04.4"],"helloMsg":{"clientHello":{"ephemeral":"ED72kH/mUiVo9V1KFI5ytevcPQEYy2QqjyVkXo1e9Aw="}},"msg":"connected to WA"}
{"level":30,"time":1731396618505,"pid":1,"hostname":"1023699f0d2f","reqId":2015,"session":"test","name":"NOWEBEngine","node":{"username":"972585251511","passive":true,"userAgent":{"platform":"WEB","appVersion":{"primary":2,"secondary":3000,"tertiary":1017531287},"mcc":"000","mnc":"000","osVersion":"0.1","manufacturer":"","device":"Desktop","osBuildNumber":"0.1","releaseChannel":"RELEASE","localeLanguageIso6391":"en","localeCountryIso31661Alpha2":"US"},"webInfo":{"webSubPlatform":"WEB_BROWSER"},"connectType":"WIFI_UNKNOWN","connectReason":"USER_ACTIVATED","device":68},"msg":"logging in..."}
{"level":30,"time":1731396618762,"pid":1,"hostname":"1023699f0d2f","reqId":2015,"session":"test","name":"NOWEBEngine","msg":"3 pre-keys found on server"}
{"level":30,"time":1731396618762,"pid":1,"hostname":"1023699f0d2f","reqId":2015,"session":"test","name":"NOWEBEngine","count":30,"msg":"uploading pre-keys"}
{"level":30,"time":1731396618915,"pid":1,"hostname":"1023699f0d2f","reqId":2015,"session":"test","name":"NOWEBEngine","count":30,"msg":"uploaded pre-keys"}
{"level":30,"time":1731396619359,"pid":1,"hostname":"1023699f0d2f","reqId":2016,"req":{"id":2016,"method":"GET","url":"/api/version","query":{},"params":{"0":"api/version"}},"res":{"statusCode":304},"responseTime":1,"msg":"request completed"}
{"level":30,"time":1731396619364,"pid":1,"hostname":"1023699f0d2f","reqId":2018,"req":{"id":2018,"method":"GET","url":"/api/server/status","query":{},"params":{"0":"api/server/status"}},"res":{"statusCode":200},"responseTime":1,"msg":"request completed"}
{"level":30,"time":1731396619370,"pid":1,"hostname":"1023699f0d2f","reqId":2017,"req":{"id":2017,"method":"GET","url":"/api/sessions?all=true","query":{"all":"true"},"params":{"0":"api/sessions"}},"res":{"statusCode":200},"responseTime":8,"msg":"request completed"}
{"level":30,"time":1731396619458,"pid":1,"hostname":"1023699f0d2f","reqId":2015,"session":"test","name":"NOWEBEngine","msg":"opened connection to WA"}
{"level":30,"time":1731396619482,"pid":1,"hostname":"1023699f0d2f","reqId":2015,"session":"test","name":"NOWEBEngine","msg":"handled 1 offline messages/notifications"}
{"level":40,"time":1731396641601,"pid":1,"hostname":"1023699f0d2f","reqId":2015,"session":"test","name":"NowebPersistentStore","msg":"got update for non-existent contact. update: '{\"id\":\"972527700007@s.whatsapp.net\",\"notify\":\"יובל אבידני\"}'"}
{"level":30,"time":1731396812298,"pid":1,"hostname":"1023699f0d2f","reqId":2015,"session":"test","name":"NOWEBEngine","trace":"Error: Connection was lost\n    at Timeout._onTimeout (/app/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:311:17)\n    at listOnTimeout (node:internal/timers:594:17)\n    at process.processTimers (node:internal/timers:529:7)","msg":"connection errored"}
{"level":30,"time":1731396812299,"pid":1,"hostname":"1023699f0d2f","reqId":2015,"session":"test","name":"WhatsappSession","msg":"Connection closed due to 'Error: Connection was lost', reconnecting..."}
{"level":30,"time":1731396812300,"pid":1,"hostname":"1023699f0d2f","reqId":2015,"session":"test","name":"WhatsappSession","job":"start-engine","class":"SingleDelayedJobRunner","msg":"Job scheduled with timeout 2000 ms"}
{"level":30,"time":1731396814303,"pid":1,"hostname":"1023699f0d2f","reqId":2015,"session":"test","name":"WhatsappSession","job":"auto-restart","class":"SinglePeriodicJobRunner","msg":"Job stopped"}
{"level":30,"time":1731396814319,"pid":1,"hostname":"1023699f0d2f","reqId":2015,"session":"test","name":"WhatsappSession","job":"auto-restart","class":"SinglePeriodicJobRunner","msg":"Job started with interval 1700000 ms"}
{"level":30,"time":1731396814439,"pid":1,"hostname":"1023699f0d2f","reqId":2015,"session":"test","name":"NOWEBEngine","browser":["Ubuntu","Chrome","22.04.4"],"helloMsg":{"clientHello":{"ephemeral":"HS5+JKHwNjWvw90aw44k2a0Iz42T7p3Q0qzjHVVlSFM="}},"msg":"connected to WA"}
{"level":30,"time":1731396814555,"pid":1,"hostname":"1023699f0d2f","reqId":2015,"session":"test","name":"NOWEBEngine","node":{"username":"972585251511","passive":true,"userAgent":{"platform":"WEB","appVersion":{"primary":2,"secondary":3000,"tertiary":1017531287},"mcc":"000","mnc":"000","osVersion":"0.1","manufacturer":"","device":"Desktop","osBuildNumber":"0.1","releaseChannel":"RELEASE","localeLanguageIso6391":"en","localeCountryIso31661Alpha2":"US"},"webInfo":{"webSubPlatform":"WEB_BROWSER"},"connectType":"WIFI_UNKNOWN","connectReason":"USER_ACTIVATED","device":68},"msg":"logging in..."}
{"level":30,"time":1731396814816,"pid":1,"hostname":"1023699f0d2f","reqId":2015,"session":"test","name":"NOWEBEngine","msg":"17 pre-keys found on server"}
{"level":30,"time":1731396814919,"pid":1,"hostname":"1023699f0d2f","reqId":2015,"session":"test","name":"NOWEBEngine","msg":"opened connection to WA"}
{"level":30,"time":1731396814972,"pid":1,"hostname":"1023699f0d2f","reqId":2015,"session":"test","name":"NOWEBEngine","msg":"handled 17 offline messages/notifications"}
{"level":50,"time":1731396815111,"pid":1,"hostname":"1023699f0d2f","reqId":2015,"session":"test","name":"NOWEBEngine","key":{"remoteJid":"972509448500-1366373688@g.us","fromMe":false,"id":"D51D04895A50B872E29B2683AD43307E","participant":"972509448500@s.whatsapp.net"},"err":{"type":"Error","message":"No SenderKeyRecord found for decryption","stack":"Error: No SenderKeyRecord found for decryption\n    at 972509448500-1366373688@g.us::972509448500::0 [as awaitable] (/app/node_modules/@adiwajshing/baileys/WASignalGroup/group_cipher.js:49:15)\n    at async _asyncQueueExecutor (/app/node_modules/@adiwajshing/baileys/WASignalGroup/queue_job.js:20:29)"},"msg":"failed to decrypt message"}
{"level":50,"time":1731396815112,"pid":1,"hostname":"1023699f0d2f","reqId":2015,"session":"test","name":"NOWEBEngine","key":{"remoteJid":"972509448500-1366373688@g.us","fromMe":false,"id":"3A0692EA08791B67722AD89F6445F1B3","participant":"972509448500@s.whatsapp.net"},"err":{"type":"Error","message":"No SenderKeyRecord found for decryption","stack":"Error: No SenderKeyRecord found for decryption\n    at 972509448500-1366373688@g.us::972509448500::0 [as awaitable] (/app/node_modules/@adiwajshing/baileys/WASignalGroup/group_cipher.js:49:15)\n    at async _asyncQueueExecutor (/app/node_modules/@adiwajshing/baileys/WASignalGroup/queue_job.js:20:29)"},"msg":"failed to decrypt message"}
{"level":50,"time":1731396815209,"pid":1,"hostname":"1023699f0d2f","reqId":2015,"session":"test","name":"NOWEBEngine","key":{"remoteJid":"120363042370618644@g.us","fromMe":false,"id":"BAE5378B6A392AFB","participant":"972556854814:8@s.whatsapp.net"},"err":{"type":"Error","message":"No SenderKeyRecord found for decryption","stack":"Error: No SenderKeyRecord found for decryption\n    at 120363042370618644@g.us::972556854814::8 [as awaitable] (/app/node_modules/@adiwajshing/baileys/WASignalGroup/group_cipher.js:49:15)\n    at async _asyncQueueExecutor (/app/node_modules/@adiwajshing/baileys/WASignalGroup/queue_job.js:20:29)"},"msg":"failed to decrypt message"}
{"level":30,"time":1731396815299,"pid":1,"hostname":"1023699f0d2f","reqId":2015,"session":"test","name":"NOWEBEngine","jid":"972526583324@s.whatsapp.net","msg":"identity changed"}
{"level":40,"time":1731396815321,"pid":1,"hostname":"1023699f0d2f","reqId":2015,"session":"test","name":"NowebPersistentStore","msg":"got receipt update for non-existent message. key: '{\"remoteJid\":\"120363316008358524@g.us\",\"id\":\"5922ED8A862B270FF552512423B929F6\",\"fromMe\":true,\"participant\":\"972505213500:44@s.whatsapp.net\"}'"}
{"level":30,"time":1731396820134,"pid":1,"hostname":"1023699f0d2f","reqId":2015,"session":"test","name":"NOWEBEngine","msgAttrs":{"from":"972509448500-1366373688@g.us","type":"text","id":"D51D04895A50B872E29B2683AD43307E","participant":"972509448500@s.whatsapp.net","offline":"1","participant_lid":"133315885588487@lid","notify":".","addressing_mode":"pn","t":"1731396686"},"retryCount":1,"msg":"sent retry receipt"}
{"level":30,"time":1731396825407,"pid":1,"hostname":"1023699f0d2f","reqId":2015,"session":"test","name":"NOWEBEngine","msgAttrs":{"from":"972509448500-1366373688@g.us","type":"text","id":"3A0692EA08791B67722AD89F6445F1B3","participant":"972509448500@s.whatsapp.net","offline":"1","participant_lid":"133315885588487@lid","notify":".","addressing_mode":"pn","t":"1731396690"},"retryCount":1,"msg":"sent retry receipt"}
{"level":40,"time":1731396830279,"pid":1,"hostname":"1023699f0d2f","reqId":2015,"session":"test","name":"NowebPersistentStore","msg":"got update for non-existent contact. update: '{\"id\":\"972584024522@s.whatsapp.net\",\"notify\":\"אוראל נהרי♠️\"}'"}
{"level":30,"time":1731396830674,"pid":1,"hostname":"1023699f0d2f","reqId":2015,"session":"test","name":"NOWEBEngine","msgAttrs":{"from":"120363042370618644@g.us","type":"text","id":"BAE5378B6A392AFB","participant":"972556854814:8@s.whatsapp.net","offline":"0","participant_lid":"176317517553750@lid","addressing_mode":"pn","notify":"972556854814","t":"1731396720"},"retryCount":1,"msg":"sent retry receipt"}
{"level":30,"time":1731396932234,"pid":1,"hostname":"1023699f0d2f","reqId":2019,"req":{"id":2019,"method":"POST","url":"/api/test/status/text","query":{},"params":{"0":"api/test/status/text"}},"res":{"statusCode":500},"err":{"type":"Error","message":"Timed Out","stack":"Error: Timed Out\n    at /app/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:147:32","data":{"stack":"Error\n    at promiseTimeout (/app/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:142:19)\n    at waitForMessage (/app/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:119:53)\n    at query (/app/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:141:22)\n    at assertSessions (/app/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:204:34)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async /app/node_modules/@adiwajshing/baileys/lib/Utils/batched.js:10:28\n    at async /app/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:376:21\n    at async Object.transaction (/app/node_modules/@adiwajshing/baileys/lib/Utils/auth-utils.js:136:26)\n    at async relayMessage (/app/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:312:9)\n    at async Object.sendMessage (/app/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:698:17)\n    at async WhatsappSessionNoWebPlus.sendTextStatus (/app/dist/core/engines/noweb/session.noweb.core.js:768:16)"},"isBoom":true,"isServer":false,"output":{"statusCode":408,"payload":{"statusCode":408,"error":"Request Time-out","message":"Timed Out"},"headers":{}}},"responseTime":288500,"msg":"request errored"}
`

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by TheOneironaut** [comment]
I tried a few more times from a different computer and different account, each time it brings a different error:

1
`[09:52:27.413] ERROR (NOWEBEngine/1): session:mal###### - failed to decrypt message {"reqId":1933,"session":"mal######","key":{"remoteJid":"status@broadcast","fromMe":false,"id":"46D99ACF4933AEA6F380494BE6673E94","participant":"9725271####@s.whatsapp.net"}} err: { "type": "Error", "message": "No SenderKeyRecord found for decryption", "stack": Error: No SenderKeyRecord found for decryption at status@broadcast::9725271####::0 [as awaitable] (/app/node_modules/@adiwajshing/baileys/WASignalGroup/group_cipher.js:49:15) at async _asyncQueueExecutor (/app/node_modules/@adiwajshing/baileys/WASignalGroup/queue_job.js:20:29)
`
2
`[09:51:14.746] INFO (1): request errored {"reqId":1932,"req":{"id":1932,"method":"POST","url":"/api/mal######/status/video","query":{},"params":{"0":"api/mal######/status/video"}},"res":{"statusCode":500},"responseTime":14900} err: { "type": "SessionError", "message": "No sessions", "stack": SessionError: No sessions at 9725871####.46 [as awaitable] (/app/node_modules/libsignal/src/session_cipher.js:71:23) at async _asyncQueueExecutor (/app/node_modules/libsignal/src/queue_job.js:20:29) "name": "SessionError" }
`
3
`{ "statusCode": 500, "timestamp": "2024-11-13T09:54:25.277Z", "exception": { "stack": "RangeError [ERR_OUT_OF_RANGE]: The value of \"value\" is out of range. It must be >= 0 and <= 255. Received 259\n at writeU_Int8 (node:internal/buffer:740:11)\n at Buffer.writeUInt8 (node:internal/buffer:750:10)\n at Object.encodeFrame (/app/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:123:19)\n at sendRawMessage (/app/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:61:29)\n at sendNode (/app/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:78:16)\n at /app/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:488:19\n at async Object.transaction (/app/node_modules/@adiwajshing/baileys/lib/Utils/auth-utils.js:136:26)\n at async relayMessage (/app/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:312:9)\n at async Object.sendMessage (/app/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:698:17)\n at async WhatsappSessionNoWebPlus.sendVideoStatus (/app/dist/plus/engines/noweb/session.noweb.plus.js:103:16)", "code": "ERR_OUT_OF_RANGE", "message": "The value of \"value\" is out of range. It must be >= 0 and <= 255. Received 259", "name": "RangeError" }, "request": { "path": "/api/mal######/status/video", "method": "POST", "body": { "file": { "mimetype": "video/mp4", "url": "https://github.com/TheOneironaut/test/raw/refs/heads/main/asdf123.mp4" }, "backgroundColor": "#38b42f" }, "query": {} }, "version": { "version": "2024.11.4", "engine": "NOWEB", "tier": "PLUS", "browser": "/usr/bin/chromium" } }
`


[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Hi! Could you try sending status in new GOWS engine 🤞  https://waha.devlike.pro/docs/how-to/engines/#gows
It should be much faster for 10K+ contacts and should have less errors.
If you encounter any - please send us full logs from docker container 🙏 waha@devlike.pro

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by yyhezkel** [comment]
> Hi! Could you try sending status in new GOWS engine 🤞 https://waha.devlike.pro/docs/how-to/engines/#gows It should be much faster for 10K+ contacts and should have less errors. If you encounter any - please send us full logs from docker container 🙏 [waha@devlike.pro](mailto:waha@devlike.pro)
> 
> [![patron:PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

is there any upcoming update for "delete" status on gows  engin?

**Comment by devlikepro** [comment]
Hi! @yyhezkel  
Please create a feature request for that, we'll prioritize based on how many people (especially supporters with the badges) wants the feature!

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
`2025.8.2` - **GOWS** - fix sending to [**🟢 Status**](https://waha.devlike.pro/docs/how-to/status/) (filter out right contacts)

-   [#1002](https://github.com/devlikeapro/waha/issues/1002) , [#1204](https://github.com/devlikeapro/waha/issues/1204) , [#413](https://github.com/devlikeapro/waha/issues/413)

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
