### ISSUE TITLE
[BUG][WEBJS] - Docker Error

### ISSUE THREAD

**Issue by ehussain** [allburov/whatsapp-http-api#444]
**Describe the bug**

Docker instance is crashing when there is incoming message, or randomly after sometime. 

**Version**

```json
{
  "version": "2024.7.5",
  "engine": "WEBJS",
  "tier": "PLUS",
  "browser": "/usr/bin/chromium"
}
```

**Docker Logs**

```
[08:16:05.303] INFO (SessionManagerPlus/30): starting session... {"reqId":833}
[08:16:05.304] INFO (WebhookConductor/30): session:60714 - Configuring webhooks for xxxxx... {"reqId":833,"session":"60714"}
[08:16:05.304] INFO (WebhookConductor/30): session:60714 - Webhooks were configured for xxxxx. {"reqId":833,"session":"60714"}
[08:16:05.310] INFO (WebhookConductor/30): session:60714 - Event 'message' is enabled for url: xxxxx {"reqId":833,"session":"60714"}
[08:16:05.310] INFO (WebhookConductor/30): session:60714 - Event 'message.any' is enabled for url: xxxxx {"reqId":833,"session":"60714"}
[08:16:05.310] INFO (WebhookConductor/30): session:60714 - Event 'message.ack' is enabled for url: xxxxx {"reqId":833,"session":"60714"}
[08:16:05.310] INFO (WebhookConductor/30): session:60714 - Event 'message.revoked' is enabled for url: xxxxx {"reqId":833,"session":"60714"}
[08:16:05.310] INFO (WebhookConductor/30): session:60714 - Event 'message.reaction' is enabled for url: xxxxx {"reqId":833,"session":"60714"}
[08:16:05.310] INFO (WebhookConductor/30): session:60714 - Event 'state.change' is enabled for url: xxxxx {"reqId":833,"session":"60714"}
[08:16:05.312] INFO (WebJSMongoAuth/30): session:60714 - Checking if session exists... {"reqId":833,"session":"60714"}
[08:16:05.320] INFO (30): request completed {"reqId":833,"req":{"id":833,"method":"POST","url":"/api/sessions/start","query":{},"params":{"0":"api/sessions/start"},"headers":{"host":"xxxxx:60714","x-api-key":"2eiZFlmzJLllfDQRLVmbDJz92UtElQUfqMIV0r22","user-agent":"GuzzleHttp/6.5.5 curl/7.58.0 PHP/7.2.33-1+ubuntu18.04.1+deb.sury.org+1","content-type":"application/json","content-length":"278"},"remoteAddress":"::ffff:167.99.242.166","remotePort":57424},"res":{"statusCode":201,"headers":{"x-powered-by":"Express","access-control-allow-origin":"*","content-type":"application/json; charset=utf-8","content-length":"292","etag":"W/\"124-SIyhgE2vFCeOej4hZBwJ/+TkI/0\""}},"responseTime":17}
[08:16:05.338] INFO (WebJSMongoAuth/30): session:60714 - Session exists: false {"reqId":833,"session":"60714"}
[08:16:05.443] ERROR (WhatsappSession/30): session:60714 - The browser has been disconnected {"reqId":826,"session":"60714"}
[08:16:05.443] DEBUG (WhatsappSession/30): session:60714 - Shouldn't restart the client, ignoring restart request {"reqId":826,"session":"60714"}
[0718/081606.199400:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0718/081606.200081:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0718/081606.205022:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0718/081606.221086:WARNING:audio_manager_linux.cc(53)] Falling back to ALSA for audio output. PulseAudio is not available or could not be initialized.
[0718/081606.276084:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.

DevTools listening on ws://127.0.0.1:35419/devtools/browser/ce31df70-ff76-4382-87c1-4386ac002928
[0718/081606.683777:INFO:CONSOLE(0)] "Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'attribution-reporting'.", source:  (0)
[0718/081606.683846:INFO:CONSOLE(0)] "Error with Permissions-Policy header: Unrecognized feature: 'battery'.", source:  (0)
[0718/081606.683872:INFO:CONSOLE(0)] "Error with Permissions-Policy header: Unrecognized feature: 'bluetooth'.", source:  (0)
[0718/081606.683916:INFO:CONSOLE(0)] "Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'compute-pressure'.", source:  (0)
[0718/081606.683940:INFO:CONSOLE(0)] "Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.", source:  (0)
[0718/081606.685203:INFO:CONSOLE(0)] "Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'shared-storage'.", source:  (0)
[0718/081606.685294:INFO:CONSOLE(0)] "Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'shared-storage-select-url'.", source:  (0)
[0718/081606.685324:INFO:CONSOLE(0)] "Error with Permissions-Policy header: Unrecognized feature: 'usb-unrestricted'.", source:  (0)
[0718/081606.923406:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0718/081606.935853:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0718/081606.936001:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0718/081606.939849:WARNING:audio_manager_linux.cc(53)] Falling back to ALSA for audio output. PulseAudio is not available or could not be initialized.
[0718/081606.987759:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.

DevTools listening on ws://127.0.0.1:46803/devtools/browser/806380f1-6738-48e7-80cc-06fdc6735f7d
[0718/081607.236876:INFO:CONSOLE(0)] "Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'attribution-reporting'.", source:  (0)
[0718/081607.237107:INFO:CONSOLE(0)] "Error with Permissions-Policy header: Unrecognized feature: 'battery'.", source:  (0)
[0718/081607.237206:INFO:CONSOLE(0)] "Error with Permissions-Policy header: Unrecognized feature: 'bluetooth'.", source:  (0)
[0718/081607.237281:INFO:CONSOLE(0)] "Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'compute-pressure'.", source:  (0)
[0718/081607.237365:INFO:CONSOLE(0)] "Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.", source:  (0)
[0718/081607.237442:INFO:CONSOLE(0)] "Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'shared-storage'.", source:  (0)
[0718/081607.237835:INFO:CONSOLE(0)] "Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'shared-storage-select-url'.", source:  (0)
[0718/081607.238195:INFO:CONSOLE(0)] "Error with Permissions-Policy header: Unrecognized feature: 'usb-unrestricted'.", source:  (0)
[08:16:06.733] INFO (SessionManagerPlus/30): Stopping 60714 session... {"reqId":834}
[08:16:06.734] INFO (SessionManagerPlus/30): "60714" has been stopped. {"reqId":834}
[08:16:06.734] INFO (SessionManagerPlus/30): Session '60714' has been stopped. {"reqId":834}
[08:16:06.737] ERROR (WhatsappSession/30): session:60714 - Navigation failed because browser has disconnected! {"reqId":833,"session":"60714"}
    err: {
      "type": "Error",
      "message": "Navigation failed because browser has disconnected!",
      "stack":
          Error: Navigation failed because browser has disconnected!
              at new LifecycleWatcher (/app/node_modules/whatsapp-web.js/node_modules/puppeteer-core/lib/cjs/puppeteer/common/LifecycleWatcher.js:95:223)
              at Frame.goto (/app/node_modules/whatsapp-web.js/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Frame.js:204:25)
              at CDPPage.goto (/app/node_modules/whatsapp-web.js/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Page.js:1083:91)
              at WebjsClient.initialize (/app/node_modules/whatsapp-web.js/src/Client.js:335:20)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async WebjsClient.initialize (/app/dist/core/engines/webjs/WebjsClient.js:9:9)
    }
[08:16:06.737] DEBUG (WhatsappSession/30): session:60714 - Shouldn't restart the client, ignoring restart request {"reqId":833,"session":"60714"}
[08:16:06.739] INFO (30): request completed {"reqId":834,"req":{"id":834,"method":"POST","url":"/api/sessions/stop","query":{},"params":{"0":"api/sessions/stop"},"headers":{"host":"xxxxx:60714","x-api-key":"2eiZFlmzJLllfDQRLVmbDJz92UtElQUfqMIV0r22","user-agent":"GuzzleHttp/6.5.5 curl/7.58.0 PHP/7.2.33-1+ubuntu18.04.1+deb.sury.org+1","content-type":"application/json","content-length":"30"},"remoteAddress":"::ffff:167.99.242.166","remotePort":57436},"res":{"statusCode":201,"headers":{"x-powered-by":"Express","access-control-allow-origin":"*"}},"responseTime":6}
[08:16:06.743] INFO (SessionManagerPlus/30): Stopping 60714 session... {"reqId":835}
[08:16:06.744] ERROR (SessionManagerPlus/30): Error while stopping session '60714' while logging out {"reqId":835}

```

[![patron:ADVANCED](https://img.shields.io/badge/patron-ADVANCED-4cd07d)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Found issue in reinjecting logic, let's try `2024.7.6` :crossed_fingers: 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
