### ISSUE TITLE
Venom engine - can not send messages

### ISSUE THREAD

**Issue by behind24proxies** [allburov/whatsapp-http-api#47]
hi , currently the docker container in unusable 
1 - issues with the web.js engine (I opened another issues for that )
2 - cannot send messages with the venom engine (unlimited spin)

more detalis : 
the venom engine works just fine , the only problem is that I cannot reply to customers
the get and the post endpoints, stopped working (unlimited spin)

I tried re-launching the container, but nothing changed

**Comment by allburov** [comment]
>1 - issues with the web.js engine (I opened another issues for that )

Fixed

> 2 - cannot send messages with the venom engine (unlimited spin)


Venom gives the error when we send a message
```
Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'isWidlike')
    at window.WAPI.window.WAPI.sendCheckType (/home/aburovqs/git/whatsapp-http-api/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:32019)
    at window.WAPI.window.WAPI.sendExist (/home/aburovqs/git/whatsapp-http-api/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:33582)
    at window.WAPI.window.WAPI.sendMessage (/home/aburovqs/git/whatsapp-http-api/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:46138)
    at pptr://__puppeteer_evaluation_script__:2:29
    at ExecutionContext._ExecutionContext_evaluate (/home/aburovqs/git/whatsapp-http-api/node_modules/puppeteer/src/common/ExecutionContext.ts:279:13)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at ExecutionContext.evaluate (/home/aburovqs/git/whatsapp-http-api/node_modules/puppeteer/src/common/ExecutionContext.ts:145:12)
    at /home/aburovqs/git/whatsapp-http-api/node_modules/venom-bot/src/api/layers/sender.layer.ts:137:22
```

**Comment by devlikepro** [comment]
Try using different engines:
- WEBJS (browser based): https://waha.devlike.pro/docs/engines/webjs/
- NOWEB (no browser, direct websocket connection): https://waha.devlike.pro/docs/engines/noweb/

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
