### ISSUE TITLE
[BUG][WEBJS] - dockor run issue after new update

### ISSUE THREAD

**Issue by Mohammed-Alugily** [allburov/whatsapp-http-api#496]
**Describe the bug**
when i pull new pro version 
i can not can run it 
i get this error : 
yarn run v1.22.19
$ node dist/main
[06:56:56.796] INFO (SessionManagerPlus/29): Using local storage for session info.
[06:56:56.802] INFO (Storage/29): Directory '/tmp/whatsapp-files' created from scratch
[06:56:55.478] INFO (Bootstrap/29): NODE - Catching unhandled exceptions enabled
[06:56:55.478] INFO (Bootstrap/29): WAHA (WhatsApp HTTP API) - Running PLUS version...
[06:56:56.810] ERROR (Bootstrap/29): Unhandled Rejection at:
[06:56:56.810] ERROR (Bootstrap/29): TypeError: this.logger.info is not a function
    at SwaggerConfiguratorPlus.configure (/app/dist/plus/SwaggerConfiguratorPlus.js:25:25)
    at bootstrap (/app/dist/main.js:52:25)
Done in 2.95s.

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Hi! fixed in `2024.8.3`, just pushed the fix :crossed_fingers: 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
