### ISSUE TITLE
[BUG][NOWEB] - Cannot read properties of null (reading 'conversation')

### ISSUE THREAD

**Issue by yeheskel2016** [allburov/whatsapp-http-api#521]
**Describe the bug**

Upgraded to 2024.9.1 from previous version and any message sent to the whatsapp number wont send a request to the webhook and will provide nontype error in the docker logs.

**Engine** I'm using **NOWEB** engine

**Docker Logs**

[12:38:04.230] ERROR (WhatsappSession/49): session:session_b2cu2w - Failed to process incoming message {"session":"session_b2cu2w","sessionRunTimestamp":1724848452249}
[12:38:04.230] ERROR (WhatsappSession/49): session:session_b2cu2w - Cannot read properties of null (reading 'conversation') {"session":"session_b2cu2w","sessionRunTimestamp":1724848452249}
    err: {
      "type": "TypeError",
      "message": "Cannot read properties of null (reading 'conversation')",
      "stack":
          TypeError: Cannot read properties of null (reading 'conversation')
              at WhatsappSessionNoWebPlus.extractBody (/app/dist/core/engines/noweb/session.noweb.core.js:958:28)
              at WhatsappSessionNoWebPlus.extractReplyTo (/app/dist/core/engines/noweb/session.noweb.core.js:976:27)
              at WhatsappSessionNoWebPlus.toWAMessage (/app/dist/core/engines/noweb/session.noweb.core.js:935:30)
              at WhatsappSessionNoWebPlus.processIncomingMessage (/app/dist/core/engines/noweb/session.noweb.core.js:921:31)
    }
Trace: TypeError: Cannot read properties of null (reading 'conversation')
    at WhatsappSessionNoWebPlus.extractBody (/app/dist/core/engines/noweb/session.noweb.core.js:958:28)
    at WhatsappSessionNoWebPlus.extractReplyTo (/app/dist/core/engines/noweb/session.noweb.core.js:976:27)
    at WhatsappSessionNoWebPlus.toWAMessage (/app/dist/core/engines/noweb/session.noweb.core.js:935:30)
    at WhatsappSessionNoWebPlus.processIncomingMessage (/app/dist/core/engines/noweb/session.noweb.core.js:921:31)
    at WhatsappSessionNoWebPlus.processIncomingMessage (/app/dist/core/engines/noweb/session.noweb.core.js:926:21)
[12:54:55.627] ERROR (WhatsappSession/49): session:session_b2cu2w - Failed to process incoming message {"session":"session_b2cu2w","sessionRunTimestamp":1724848452249}
[12:54:55.627] ERROR (WhatsappSession/49): session:session_b2cu2w - Cannot read properties of null (reading 'conversation') {"session":"session_b2cu2w","sessionRunTimestamp":1724848452249}
    err: {
      "type": "TypeError",
      "message": "Cannot read properties of null (reading 'conversation')",
      "stack":
          TypeError: Cannot read properties of null (reading 'conversation')
              at WhatsappSessionNoWebPlus.extractBody (/app/dist/core/engines/noweb/session.noweb.core.js:958:28)
              at WhatsappSessionNoWebPlus.extractReplyTo (/app/dist/core/engines/noweb/session.noweb.core.js:976:27)
              at WhatsappSessionNoWebPlus.toWAMessage (/app/dist/core/engines/noweb/session.noweb.core.js:935:30)
              at WhatsappSessionNoWebPlus.processIncomingMessage (/app/dist/core/engines/noweb/session.noweb.core.js:921:31)
    }

Note:
Downgraded back to NOWEB (2024.8.5) and everything is working well.

**Comment by devlikepro** [comment]
Fixed in `2024.9.2` :crossed_fingers: 

Remember that you can always pin the docker version in case of any errors with new one

https://waha.devlike.pro/docs/how-to/engines/#versions
```
devlikeapro/waha-plus:latest-2024.8.5
```



[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
@yeheskel2016 thank you for such detailed report, it helped a lot! :bow: 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by johnyfernandes** [comment]
Hello! I am having the same exact issue! From ChatWoot to WhatsApp, it works perfectly. But from WhatsApp to ChatWoot, it never triggers the webhook :(

```
[17:05:57.714] ERROR (WhatsappSession/37): session:john - Failed to process incoming message {"reqId":4265,"session":"john","sessionRunTimestamp":1736183059169}
[17:05:57.714] ERROR (WhatsappSession/37): session:john - Cannot read properties of null (reading 'conversation') {"reqId":4265,"session":"john","sessionRunTimestamp":1736183059169}
    err: {
      "type": "TypeError",
      "message": "Cannot read properties of null (reading 'conversation')",
      "stack":
          TypeError: Cannot read properties of null (reading 'conversation')
              at WhatsappSessionNoWebPlus.extractBody (/app/dist/core/engines/noweb/session.noweb.core.js:958:28)
              at WhatsappSessionNoWebPlus.extractReplyTo (/app/dist/core/engines/noweb/session.noweb.core.js:976:27)
              at WhatsappSessionNoWebPlus.toWAMessage (/app/dist/core/engines/noweb/session.noweb.core.js:935:30)
              at WhatsappSessionNoWebPlus.processIncomingMessage (/app/dist/core/engines/noweb/session.noweb.core.js:921:31)
    }
```

Those are the only logs, from Docker.
