### ISSUE TITLE
[BUG][NOWEB] -  I don’t know what causes the FAILED status to appear.

### ISSUE THREAD

**Issue by HuangDaHui** [allburov/whatsapp-http-api#531]
I've tried restart, stop, and start but it doesn't work.
Can only be deleted and re-created
{
  "statusCode": 500,
  "timestamp": "2024-09-06T01:22:43.919Z",
  "exception": {
    "stack": "Error: Connection Closed\n    at sendRawMessage (/app/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:59:19)\n    at sendNode (/app/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:78:16)\n    at query (/app/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:142:15)\n    at getUSyncDevices (/app/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:168:30)\n    at /app/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:401:57\n    at Object.transaction (/app/node_modules/@adiwajshing/baileys/lib/Utils/auth-utils.js:136:32)\n    at relayMessage (/app/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:307:30)\n    at Object.sendMessage (/app/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:677:23)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
    "message": "Connection Closed",
    "data": null,
    "isBoom": true,
    "isServer": false,
    "output": {},
    "name": "Error"
  },
  "request": {
    "path": "/api/sendText",
    "method": "POST",
    "body": {
      "chatId": "11111111111@c.us",
      "text": "Hi there!",
      "session": "848719"
    },
    "query": {}
  },
  "version": {
    "version": "2024.9.2",
    "engine": "NOWEB",
    "tier": "PLUS",
    "browser": "/usr/bin/chromium"
  }
}

**Comment by devlikepro** [comment]
Hi! Is there any logs in the container about that? Likely it retries reconnecting over and over like every 2 seconds

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by HuangDaHui** [comment]
> Hi! Is there any logs in the container about that? Likely it retries reconnecting over and over like every 2 seconds
> 
> [![patron:PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

I need to check it out, it just stays FAILED and doesn't work properly

**Comment by kitobelix** [comment]
Hey, I have this strange behavior in one of my sessions and happens from time to time. What do you need to debug?

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Hi! Try updating to `2025.7.5`, it updates some internal protocols 🤞 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
