### ISSUE TITLE
[BUG][NOWEB] - Connection Closed

### ISSUE THREAD

**Issue by kevinnadar22** [allburov/whatsapp-http-api#532]
> While sending text using POST Method, I'm getting Error: Connection Closed

**Version**

```json
{
  "version": "2024.9.1",
  "engine": "NOWEB",
  "tier": "PLUS",
  "browser": "/usr/bin/google-chrome-stable"
}
```

**Engine** I'm using **NOWEB** engine.

**Requests - Responses**

 ```json
{
  "statusCode": 500,
  "timestamp": "2024-09-06T13:23:50.231Z",
  "exception": {
    "stack": "Error: Connection Closed\n    at sendRawMessage (/app/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:59:19)\n    at sendNode (/app/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:78:16)\n    at query (/app/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:142:15)\n    at getUSyncDevices (/app/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:168:30)\n    at /app/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:401:57\n    at Object.transaction (/app/node_modules/@adiwajshing/baileys/lib/Utils/auth-utils.js:136:32)\n    at relayMessage (/app/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:307:30)\n    at Object.sendMessage (/app/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:677:23)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
    "message": "Connection Closed",
    "data": null,
    "isBoom": true,
    "isServer": false,
    "output": {},
    "name": "Error"
  },
  "request": {
    "path": "/api/sendText",
    "method": "POST",
    "body": {
      "chatId": "11111111111@c.us",
      "reply_to": null,
      "text": "Hi there!",
      "session": "warmer_tt"
    },
    "query": {}
  },
  "version": {
    "version": "2024.9.1",
    "engine": "NOWEB",
    "tier": "PLUS",
    "browser": "/usr/bin/chromium"
  }
}
```

**Comment by devlikepro** [comment]
hi! Does the session restart or retry helps with this error?
We reconnect the session every 30 minutes and it's not available for about 2 seconds during this time - it could be this issue.

May be you could attach docker container logs for this case? It'd really help :pray: 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
