### ISSUE TITLE
Error 500 when sending to mulltiple recipients

### ISSUE THREAD

**Issue by anti-government** [allburov/whatsapp-http-api#541]
Does waha support sending multiple recipients ? 
im tryinng to send a bulk message

```
{
  "chatIds": [
    "11111111111@c.us",
    "22222222222@c.us",
    "33333333333@c.us"
  ],
  "text": "Hi there!",
  "session": "default"
}
```
responses
        
```
{
  "statusCode": 500,
  "timestamp": "2024-09-11T10:34:55.108Z",
  "exception": {
    "stack": "TypeError: Cannot read properties of undefined (reading 'includes')\n    at ensureSuffix (/app/dist/core/abc/session.abc.js:20:15)\n    at WhatsappSessionWebJSCore.ensureSuffix (/app/dist/core/abc/session.abc.js:306:16)\n    at WhatsappSessionWebJSCore.sendText (/app/dist/core/engines/webjs/session.webjs.core.js:218:47)\n    at ChattingController.sendText (/app/dist/api/chatting.controller.js:27:25)\n    at /app/node_modules/@nestjs/core/router/router-execution-context.js:38:29\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
    "message": "Cannot read properties of undefined (reading 'includes')",
    "name": "TypeError"
  },
  "request": {
    "path": "/api/sendText",
    "method": "POST",
    "body": {
      "chatIds": [
        "11111111111@c.us",
        "22222222222@c.us",
        "33333333333@c.us"
      ],
      "text": "Hi there!",
      "session": "default"
    },
    "query": {}
  },
  "version": {
    "version": "2024.9.4",
    "engine": "WEBJS",
    "tier": "CORE",
    "browser": "/usr/bin/chromium"
  }
}
```

or im doing this wrong ? please kindly help

**Comment by devlikepro** [comment]
It's not supported by default, only single `chatId` is accepted 

You can send multiple HTTP requests in for loop or automation using n8n:
https://waha.devlike.pro/docs/integrations/n8n/

Here's template for that
https://waha-n8n-templates.devlike.pro/send-bulk-messages/
```bash
curl -X POST -H "Content-Type: application/json" -d '[
    {
        "text": "Hi there!",
        "phone": "123123"
    },
        {
        "text": "Hi there!",
        "phone": "123123"
    },
        {
        "text": "Hi there!",
        "phone": "123123"
    },
    {
        "text": "Hi there!",
        "phone": "123123"
    }
]' https://localhost:5000/webhook/11111111-111111-1111-1111-d2ac95896744/messages/{SESSION}/bulk
```

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
