### ISSUE TITLE
[BUG][WEBJS] - Unable to send reply to specific message

### ISSUE THREAD

**Issue by ehussain** [allburov/whatsapp-http-api#576]
**Describe the bug**

When I reply to specific version then message should be sent.

**Version**

```json
{
  "version": "2024.10.3",
  "engine": "WEBJS",
  "tier": "PLUS",
  "browser": "/usr/bin/google-chrome-stable"
}
```

**To Reproduce** Steps to reproduce the behavior:
Pick any message and send reply_to.

**Expected behavior**

It should send a reply to the message

**Engine** I'm using **WEBJS** engine.

**Requests - Responses**

```
POST /api/reply
{"chatId":"xcxxx@c.us","session":"xxxx","type":"text","text":".","reply_to":"false_xxxxx@c.us_12D20EC2E7A34340A1EFF8D747EXXXX"}

{"statusCode":500,"timestamp":"2024-10-09T03:08:08.071Z","exception":{"stack":"Error: Evaluation failed: Error: Could not get the quoted message.\n    at new Error (<anonymous>:6:31)\n    at window.WWebJS.sendMessage (pptr://__puppeteer_evaluation_script__:50:23)\n    at async pptr://__puppeteer_evaluation_script__:10:25\n    at ExecutionContext._ExecutionContext_evaluate (/app/node_modules/whatsapp-web.js/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:229:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ExecutionContext.evaluate (/app/node_modules/whatsapp-web.js/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)\n    at async WebjsClient.sendMessage (/app/node_modules/whatsapp-web.js/src/Client.js:956:25)","message":"Evaluation failed: Error: Could not get the quoted message.\n    at new Error (<anonymous>:6:31)\n    at window.WWebJS.sendMessage (pptr://__puppeteer_evaluation_script__:50:23)\n    at async pptr://__puppeteer_evaluation_script__:10:25","name":"Error"},"request":{"path":"/api/reply","method":"POST","body":{"chatId":"xxxxxxx@c.us","session":"xxxxx","type":"text","text":".","reply_to":"false_xxxxxxx@c.xxxxxxxxxxx"},"query":{}},"version":{"version":"2024.10.3","engine":"WEBJS","tier":"PLUS","browser":"/usr/bin/google-chrome-stable"}}

```

**Docker Logs**

```
[03:08:08.071] INFO (15): request errored {"reqId":11,"req":{"id":11,"method":"POST","url":"/api/reply","query":{},"params":{"0":"api/reply"}},"res":{"statusCode":500},"responseTime":4}
    err: {
      "type": "Error",
      "message": "Evaluation failed: Error: Could not get the quoted message.\n    at new Error (<anonymous>:6:31)\n    at window.WWebJS.sendMessage (pptr://__puppeteer_evaluation_script__:50:23)\n    at async pptr://__puppeteer_evaluation_script__:10:25",
      "stack":
          Error: Evaluation failed: Error: Could not get the quoted message.
              at new Error (<anonymous>:6:31)
              at window.WWebJS.sendMessage (pptr://__puppeteer_evaluation_script__:50:23)
              at async pptr://__puppeteer_evaluation_script__:10:25
              at ExecutionContext._ExecutionContext_evaluate (/app/node_modules/whatsapp-web.js/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:229:15)
              at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
              at async ExecutionContext.evaluate (/app/node_modules/whatsapp-web.js/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)
              at async WebjsClient.sendMessage (/app/node_modules/whatsapp-web.js/src/Client.js:956:25)
    }

```

[![patron:ADVANCED](https://img.shields.io/badge/patron-ADVANCED-4cd07d)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by HuangDaHui** [comment]
+1

**Comment by devlikepro** [comment]
Added 5 retries with 100ms delay, if at the end it doesn't work - it'll fallback to regular message, not reply one

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
