### ISSUE TITLE
[BUG][NOWEB] - Webhook Fails with 'Cannot read properties of undefined (reading X-Webhook-Request-Id)' Error

### ISSUE THREAD

**Issue by WittmannF** [allburov/whatsapp-http-api#595]
**Describe the bug**

When setting up a webhook using either `webhook.site` or a local FastAPI server, the webhook fails with a series of `TypeError: Cannot read properties of undefined (reading 'X-Webhook-Request-Id')` errors. This occurs when attempting to send events through the configured webhook URL.

Error logs:

No message posted to the webhook. Also the following on docker:

```
[23:39:23.750] ERROR (Bootstrap/1): Unhandled Rejection at:
[23:39:23.751] ERROR (Bootstrap/1): TypeError: Cannot read properties of undefined (reading 'X-Webhook-Request-Id')
    at WebhookSenderCore.send (/app/dist/core/webhooks.core.js:28:39)
    at WebhookConductorCore.callWebhook (/app/dist/core/webhooks.core.js:123:16)
    at /app/dist/core/webhooks.core.js:103:28
    at EventEmitter.<anonymous> (/app/dist/core/engines/noweb/session.noweb.core.js:828:62)
    at EventEmitter.emit (node:events:532:35)
    at EventEmitter.<anonymous> (/app/node_modules/@adiwajshing/baileys/lib/Utils/event-buffer.js:40:16)
    at EventEmitter.emit (node:events:520:28)
    at Object.emit (/app/node_modules/@adiwajshing/baileys/lib/Utils/event-buffer.js:94:23)
    at WebSocketClient.handlePresenceUpdate (/app/node_modules/@adiwajshing/baileys/lib/Socket/chats.js:566:16)
    at WebSocketClient.emit (node:events:520:28)
    at /app/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:241:35
    at Object.decodeFrame (/app/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:149:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
[23:39:23.876] ERROR (Bootstrap/1): Unhandled Rejection at:
[23:39:23.876] ERROR (Bootstrap/1): TypeError: Cannot read properties of undefined (reading 'X-Webhook-Request-Id')
    at WebhookSenderCore.send (/app/dist/core/webhooks.core.js:28:39)
    at WebhookConductorCore.callWebhook (/app/dist/core/webhooks.core.js:123:16)
    at /app/dist/core/webhooks.core.js:103:28
    at EventEmitter.<anonymous> (/app/dist/core/engines/noweb/session.noweb.core.js:828:62)
    at EventEmitter.emit (node:events:532:35)
    at EventEmitter.<anonymous> (/app/node_modules/@adiwajshing/baileys/lib/Utils/event-buffer.js:40:16)
    at EventEmitter.emit (node:events:520:28)
    at Object.emit (/app/node_modules/@adiwajshing/baileys/lib/Utils/event-buffer.js:94:23)
    at EventEmitter.<anonymous> (/app/dist/core/engines/noweb/session.noweb.core.js:310:128)
    at EventEmitter.emit (node:events:532:35)
    at EventEmitter.<anonymous> (/app/node_modules/@adiwajshing/baileys/lib/Utils/event-buffer.js:40:16)
    at EventEmitter.emit (node:events:520:28)
    at Object.flush (/app/node_modules/@adiwajshing/baileys/lib/Utils/event-buffer.js:73:16)
    at processNodeWithBuffer (/app/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:853:12)
[23:39:23.876] ERROR (Bootstrap/1): Unhandled Rejection at:
[23:39:23.876] ERROR (Bootstrap/1): TypeError: Cannot read properties of undefined (reading 'X-Webhook-Request-Id')
    at WebhookSenderCore.send (/app/dist/core/webhooks.core.js:28:39)
    at WebhookConductorCore.callWebhook (/app/dist/core/webhooks.core.js:123:16)
    at /app/dist/core/webhooks.core.js:103:28
    at /app/dist/core/engines/noweb/session.noweb.core.js:941:17
[23:39:23.876] ERROR (Bootstrap/1): Unhandled Rejection at:
[23:39:23.876] ERROR (Bootstrap/1): TypeError: Cannot read properties of undefined (reading 'X-Webhook-Request-Id')
    at WebhookSenderCore.send (/app/dist/core/webhooks.core.js:28:39)
    at WebhookConductorCore.callWebhook (/app/dist/core/webhooks.core.js:123:16)
    at /app/dist/core/webhooks.core.js:103:28
    at /app/dist/core/engines/noweb/session.noweb.core.js:941:17
[23:39:23.876] ERROR (Bootstrap/1): Unhandled Rejection at:
[23:39:23.876] ERROR (Bootstrap/1): TypeError: Cannot read properties of undefined (reading 'X-Webhook-Request-Id')
    at WebhookSenderCore.send (/app/dist/core/webhooks.core.js:28:39)
    at WebhookConductorCore.callWebhook (/app/dist/core/webhooks.core.js:123:16)
    at /app/dist/core/webhooks.core.js:103:28
    at /app/dist/core/engines/noweb/session.noweb.core.js:941:17
[23:39:23.876] ERROR (Bootstrap/1): Unhandled Rejection at:
[23:39:23.876] ERROR (Bootstrap/1): TypeError: Cannot read properties of undefined (reading 'X-Webhook-Request-Id')
    at WebhookSenderCore.send (/app/dist/core/webhooks.core.js:28:39)
    at WebhookConductorCore.callWebhook (/app/dist/core/webhooks.core.js:123:16)
    at /app/dist/core/webhooks.core.js:103:28
    at /app/dist/core/engines/noweb/session.noweb.core.js:941:17

```

I tried multiple configurations, but the webhook is not being triggered properly.

**Version**

```json
{
  "version": "2023.11.1",
  "engine": "NOWEB",
  "tier": "FREE",
  "browser": "/usr/bin/google-chrome-stable"
}
```

**To Reproduce**

1. Go to `/api/sessions/` and start a session with the following payload:

   ```json
   {
     "name": "default",
     "config": {
       "webhooks": [
         {
           "url": "https://webhook.site/your-unique-id",
           "events": ["message"]
         }
       ]
     }
   }
   ```

2. Start the session.
3. Send a WhatsApp message to the connected number.
4. Observe the errors in the logs.

**Expected behavior**

The webhook should trigger and send the event payload to the configured URL without generating errors. The FastAPI server or `webhook.site` should receive the payload correctly.

**Engine**

I tried with both the **NOWEB** and **WEBJS** engine.

**Requests - Responses**

Here’s the request I used to configure the webhook:

```json
{
  "name": "default",
  "config": {
    "webhooks": [
      {
        "url": "https://webhook.site/your-unique-id",
        "events": ["message"]
      }
    ]
  }
}
```

I didn’t receive any responses on the webhook endpoint due to the errors.

**Additional context**

I tested this with both a local FastAPI server and `webhook.site`. The errors seem to suggest that the webhook request headers may not be properly handled. Would appreciate any guidance on resolving this issue. Here's how I implemented the webhook locally:

```python
import logging
from fastapi import FastAPI, Request

app = FastAPI()

# Configure logging
logging.basicConfig(level=logging.INFO)

@app.post("/webhook")
async def receive_webhook(request: Request):
    logging.info("Received webhook request")
    data = await request.json()
    logging.info(f"Received data: {data}")
    return {"status": "received", "data": data}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
```

**Comment by devlikepro** [comment]
@WittmannF thank you for the report! Let's try `2024.10.7`, fixed the issue there :crossed_fingers: 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by WittmannF** [comment]
Awesome @devlikepro ! I've made a hotfix on my side in the meantime. Thank you for this wonderful project!

**Comment by devlikepro** [comment]
good to know! :clap: 
feel free to create a PR with the changes if you know how to fix the issue, it'd help the project a lot! :+1: 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
