### ISSUE TITLE
[BUG][WEBJS] - Error Inquiry for Phone Number Check

### ISSUE THREAD

**Issue by tiarsagitar** [allburov/whatsapp-http-api#619]
### Describe the bug

I am encountering an error when checking a phone number using the endpoint /api/contacts/check-exists

### Version

Get the WAHA version 2024.10.8 by calling `GET api/contacts/check-exists.`

```json
{
    "status": "error",
    "message": "Request failed with status code 500",
    "error": {
        "statusCode": 500,
        "timestamp": "2024-10-31T02:20:39.428Z",
        "exception": {
            "stack": "Error: rate-overlimit\n    at assertNodeErrorFree (/app/node_modules/@adiwajshing/baileys/lib/WABinary/generic-utils.js:56:15)\n    at query (/app/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:145:48)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async interactiveQuery (/app/node_modules/@adiwajshing/baileys/lib/Socket/chats.js:116:24)\n    at async Object.onWhatsApp (/app/node_modules/@adiwajshing/baileys/lib/Socket/chats.js:168:25)\n    at async WhatsappSessionNoWebPlus.checkNumberStatus (/app/dist/core/engines/noweb/session.noweb.core.js:377:26)",
            "message": "rate-overlimit",
            "data": 429,
            "isBoom": true,
            "isServer": true,
            "output": {},
            "name": "Error"
        },
        "request": {
            "path": "/api/contacts/check-exists?session=session&phone=089535",
            "method": "GET",
            "body": {},
            "query": {
                "session": "session",
                "phone": "089535"
            }
        },
        "version": {
            "version": "2024.10.8",
            "engine": "NOWEB",
            "tier": "PLUS",
            "browser": "/usr/bin/chromium"
        }
    }
}
```

**Comment by devlikepro** [comment]
Hi! Try to restart a session or pair a new one.
The error comes from WA server, nothing we can do here :( 

Rate limit it and cache the result on your side (if you check it for every chats you have) - that's only thing we can suggest here

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
