### ISSUE TITLE
Error from nowhere. Not avaliable to send any msg on plus.

### ISSUE THREAD

**Issue by doutorinfamous** [allburov/whatsapp-http-api#62]
```
"statusCode": 500,
    "timestamp": "2023-02-19T10:53:20.970Z",
    "exception": {
        "stack": "Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.\n    at CDPSession.send (/app/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:218:35)\n    at ExecutionContext._evaluateInternal (/app/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:204:50)\n    at ExecutionContext.evaluate (/app/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:27)\n    at DOMWorld.evaluate (/app/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:97:24)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
        "message": "Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.",
        "name": "Error"

```

The api was working fine last night, when i wake up the bot isn't sending msgs anymore. That error is in place now.

**Comment by doutorinfamous** [comment]
Fixed.
