### ISSUE TITLE
[BUG][WEBJS] - Bug when creating an invite code through the API

### ISSUE THREAD

**Issue by maxbellec** [allburov/whatsapp-http-api#661]
### Describe the bug

Can't create an invite code with the API.

### Version

Get the WAHA version by calling `GET /api/version`

```json
{"version":"2024.11.8","engine":"WEBJS","tier":"PLUS","browser":"/usr/bin/google-chrome-stable"}
```
Same issue on older 2024.8.2.

## Steps

1. `curl -H "X-Api-Key: XXX" https://waha.telescoop.fr/api/session_xmv2c/groups/XXX@g.us/invite-code`

### Expected behavior

Returns an invite code

### Response

```json
{"statusCode":500,"timestamp":"2024-11-25T10:19:45.179Z","exception":{"stack":"TypeError: groupChat.getInviteCode is not a function\n    at WhatsappSessionWebJSPlus.getInviteCode (/app/dist/core/engines/webjs/session.webjs.core.js:538:26)","message":"groupChat.getInviteCode is not a function","name":"TypeError"},"request":{"path":"/api/session_xmv2c/groups/120363349974676714@g.us/invite-code","method":"GET","body":{},"query":{}},"version":{"version":"2024.11.8","engine":"WEBJS","tier":"PLUS","browser":"/usr/bin/google-chrome-stable"}}
```

### Docker Logs

```
[10:24:50.495] INFO (1): request errored {"reqId":274,"req":{"id":274,"method":"GET","url":"/api/session_xmv2c/groups/120363369826496000@g.us/invite-code","query":{},"params":{"0":"api/session_xmv2c/groups/120363369826496000@g.us/invite-code"}},"res":{"statusCode":500},"responseTime":4}
    err: {
      "type": "TypeError",
      "message": "groupChat.getInviteCode is not a function",
      "stack":
          TypeError: groupChat.getInviteCode is not a function
              at WhatsappSessionWebJSPlus.getInviteCode (/app/dist/core/engines/webjs/session.webjs.core.js:538:26)
    }

```

**Comment by devlikepro** [comment]
Hi! Try updating to 2024.11.10 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
