### ISSUE TITLE
[BUG][WEBJS] - Error listing channels

### ISSUE THREAD

**Issue by ijro** [allburov/whatsapp-http-api#664]
API /api/{session}/channels returns error

Version: Version: Waha Plus (ARM) 2024.11.8 WEBJS

Error: TypeError: Cannot read properties of undefined (reading 'membershipType')

```json
{
  "statusCode": 500,
  "timestamp": "2024-11-25T20:27:46.049Z",
  "exception": {
    "stack": "TypeError: Cannot read properties of undefined (reading 'membershipType')\n    at ChatToChannel (/app/dist/core/engines/webjs/session.webjs.core.js:571:29)\n    at Array.map (<anonymous>)\n    at WhatsappSessionWebJSPlus.channelsList (/app/dist/core/engines/webjs/session.webjs.core.js:604:29)",
    "message": "Cannot read properties of undefined (reading 'membershipType')",
    "name": "TypeError"
  },
  "request": {
    "path": "/api/SPLASHANDGO/channels?role=ADMIN",
    "method": "GET",
    "body": {},
    "query": {
      "role": "ADMIN"
    }
  },
  "version": {
    "version": "2024.11.8",
    "engine": "WEBJS",
    "tier": "PLUS",
    "browser": "/usr/bin/chromium"
  }
}
```

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Hi! Try `2024.11.11`

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
