### ISSUE TITLE
[BUG][WEBJS] - Internal server error when trying to send video using sendVideo endpoint.

### ISSUE THREAD

**Issue by azizmhmmdf** [allburov/whatsapp-http-api#668]
### Describe the bug

A clear and concise description of what the bug is. Feel free to remove sections
that you don't feel to make the text shorter!

### Version

Get the WAHA version by calling `GET /api/version`

```json
{
 "version": "2024.11.8",
  "engine": "WEBJS",
  "tier": "PLUS",
  "browser": "/usr/bin/google-chrome-stable"
}
```

Try to update to
[the latest version](https://github.com/devlikeapro/waha/releases) before
creating an issue!

## Steps

**To Reproduce** Steps to reproduce the behavior:

1. Open swagger url: /#/:outbox_tray:%20Chatting/ChattingController_sendVideo
2. Change session and chatId, and send the example json.
3. See error

### Expected behavior

Should send video to the given chatId.

### Requests - Responses

Request:
You can use example json.
Response:
```json
{
  "statusCode": 500,
  "timestamp": "2024-11-26T13:24:49.835Z",
  "exception": {
    "stack": "a: a\n    at #evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:388:56)\n    at async ExecutionContext.evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:275:16)\n    at async IsolatedWorld.evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/IsolatedWorld.js:100:16)\n    at async CdpFrame.evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Frame.js:341:20)\n    at async CdpPage.evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Page.js:807:20)\n    at async WebjsClient.sendMessage (/app/node_modules/whatsapp-web.js/src/Client.js:956:25)",
    "message": "a",
    "name": "a"
  },
  "request": {
    "path": "/api/sendVideo",
    "method": "POST",
    "body": {
      "chatId": "6281384242232@c.us",
      "file": {
        "mimetype": "video/mp4",
        "filename": "video.mp4",
        "url": "https://github.com/devlikeapro/waha/raw/core/examples/video.mp4"
      },
      "reply_to": null,
      "asNote": false,
      "caption": "Just watch at this!",
      "session": "blast10"
    },
    "query": {}
  },
  "version": {
    "version": "2024.11.8",
    "engine": "WEBJS",
    "tier": "PLUS",
    "browser": "/usr/bin/chromium"
  }
}
```

**Comment by devlikepro** [comment]
In your response it says:

> /usr/bin/chromium

Try  using chrome based image `devlikeapro/waha-plus:chrome`

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
https://waha.devlike.pro/docs/how-to/engines/#examples

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by DidiDerDenker** [comment]
@devlikepro I'm experiencing the same error, even when I'm using the chrome-image. Video is 9:16 and public available here: https://alpinlabsstorage.blob.core.windows.net/queue/cfb44d27-dae2-492c-9acc-29cab2c86087.mp4

I'd be happy if you can help or inform us what to do and what video specs may be difficult to post to channels.

Logs:

[12:17:11.526] INFO (48): request errored {"reqId":3,"req":{"id":3,"method":"POST","url":"/api/sendVideo","query":{},"params":{"path":["api","sendVideo"]}},"res":{"statusCode":500},"responseTime":4610}
    err: {
      "type": "Error",
      "message": "t",
      "stack":
          t: t
              at #evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:391:56)
              at async ExecutionContext.evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:277:16)
              at async IsolatedWorld.evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/IsolatedWorld.js:100:16)
              at async CdpFrame.evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Frame.js:364:20)
              at async CdpPage.evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Page.js:822:20)
              at async WPage.evaluate (/app/dist/core/engines/webjs/WPage.js:13:20)
              at async WebjsClientPlus.sendMessage (/app/node_modules/whatsapp-web.js/src/Client.js:1048:25)
              at async descriptor.value (/app/dist/core/abc/activity.js:9:20)
      "name": "t"
    }

**Comment by devlikepro** [comment]
@DidiDerDenker Could you try to restart or repair (logout / scan qr code) the session?

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
and use 2025.11.2 version

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by DidiDerDenker** [comment]
Thanks for your response, appreciate it! I'll try it with this version.

**Comment by DidiDerDenker** [comment]
We waited a few weeks but could still see some errors, for example a) and b) as follows. Maybe the issues are connected to each other and you can help? Would be great, thank you! :)

**a)** This error occurs when posting videos, even though it works with other videos with the same code architecture.

[09:14:11.000] INFO (48): request errored {"reqId":969,"req":{"id":969,"method":"POST","url":"/api/sendVideo","query":{},"params":{"path":["api","sendVideo"]}},"res":{"statusCode":422},"responseTime":10036}
    err: {
      "type": "UnprocessableEntityException",
      "message": "Unprocessable Entity Exception",
      "stack":
          UnprocessableEntityException: Unprocessable Entity Exception
              at SessionManagerPlus.waitUntilStatus (/app/dist/core/abc/manager.abc.js:111:19)
              at async ChattingController.sendVideo (/app/dist/api/chatting.controller.js:59:26)
      "response": {
        "error": "Session status is not as expected. Try again later or restart the session",
        "session": "32ca9c09-8ade-495f-9a31-a5c0de872e78",
        "status": "FAILED",
        "expected": [
          "WORKING"
        ]
      },
      "status": 422,
      "options": {},
      "name": "UnprocessableEntityException"

**b)** This error occrus sometimes when trying to post a message. There seems to be an error with the Chromium engine because it gets shut down even though the session is working. This is why some messages can not be sent to channels on time.

[07:05:37.706] INFO (48): request errored {"reqId":918,"req":{"id":918,"method":"POST","url":"/api/sendImage","query":{},"params":{"path":["api","sendImage"]}},"res":{"statusCode":500},"responseTime":302039}
    err: {
      "type": "TargetCloseError",
      "message": "Protocol error (Runtime.callFunctionOn): Target closed: ",
      "stack":
          TargetCloseError: Protocol error (Runtime.callFunctionOn): Target closed
              at CallbackRegistry.clear (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:81:36)
              at CdpCDPSession.onClosed (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/CdpSession.js:114:25)
              at #onClose (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:181:21)
              at Connection.dispose (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:187:22)
              at CdpBrowser.disconnect (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Browser.js:238:26)
              at CdpBrowser.close (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Browser.js:234:20)
              at async WebjsClientPlus.destroy (/app/node_modules/whatsapp-web.js/src/Client.js:873:9)
              at async WebjsClientPlus.destroy (/app/dist/core/engines/webjs/WebjsClientCore.js:87:9)
              at async WhatsappSessionWebJSPlus.end (/app/dist/core/engines/webjs/session.webjs.core.js:233:13)
              at async /app/dist/core/engines/webjs/session.webjs.core.js:126:13
          caused by: ProtocolError
              at <instance_members_initializer> (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:102:14)
              at new Callback (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:106:16)
              at CallbackRegistry.create (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:24:26)
              at Connection._rawSend (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:99:26)
              at CdpCDPSession.send (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/CdpSession.js:73:33)
              at #evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:363:50)
              at ExecutionContext.evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:277:36)
              at IsolatedWorld.evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/IsolatedWorld.js:100:30)
              at CdpFrame.evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Frame.js:364:43)
              at CdpFrame.<anonymous> (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/util/decorators.js:109:27)
              at CdpPage.evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Page.js:822:43)
              at WPage.evaluate (/app/dist/core/engines/webjs/WPage.js:13:36)
              at WebjsClientPlus.sendMessage (/app/node_modules/whatsapp-web.js/src/Client.js:1062:44)
              at WhatsappSessionWebJSPlus.sendImage (/app/dist/plus/engines/webjs/session.webjs.plus.js:78:30)
              at process.processTicksAndRejections (node:internal/process/task_queues:103:5)
              at async descriptor.value (/app/dist/core/abc/activity.js:9:20)
      "name": "TargetCloseError"
    }
