### ISSUE TITLE
[BUG][WEBJS] - Sessions Not Starting

### ISSUE THREAD

**Issue by whera** [allburov/whatsapp-http-api#691]
After updating to the version:

```json
{
  "version": "2024.12.3",
  "engine": "WEBJS",
  "tier": "PLUS",
  "browser": "/usr/bin/chromium"
}
```

I encountered an issue where existing sessions cannot be started. They remain stuck in the STARTING status and do not proceed.
When checking the logs, the following error is displayed:
```bash
[12:49:37.275] ERROR (WhatsappSession/1): session:1705 - Runtime.callFunctionOn timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed. {"reqId":770,"session":"1705"}
    err: {
      "type": "ProtocolError",
      "message": "Runtime.callFunctionOn timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.",
      "stack":
          ProtocolError: Runtime.callFunctionOn timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
              at <instance_members_initializer> (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:94:14)
              at new Callback (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:98:16)
              at CallbackRegistry.create (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:23:26)
              at Connection._rawSend (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:90:26)
              at CdpCDPSession.send (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/CDPSession.js:66:33)
              at #evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:360:50)
              at ExecutionContext.evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:275:36)
              at IsolatedWorld.evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/IsolatedWorld.js:100:30)
              at CdpFrame.evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Frame.js:341:43)
              at CdpFrame.<anonymous> (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/util/decorators.js:104:27)
              at CdpPage.evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Page.js:807:43)
              at WebjsClient.inject (/app/node_modules/whatsapp-web.js/src/Client.js:107:55)
              at async WebjsClient.initialize (/app/node_modules/whatsapp-web.js/src/Client.js:334:9)
      "name": "ProtocolError"
    }
```

**Comment by evollution** [comment]
I have same problem all my sessions remain in status starting

[11:06:19.635] INFO (1): request errored {"reqId":168,"req":{"id":168,"method":"GET","url":"/api/contacts/check-exists?phone=&session=session_","query":{"phone":"40723468122","session":"session_"},"params":{"0":"api/contacts/check-exists"}},"res":{"statusCode":422},"responseTime":6090}
    err: {
      "type": "UnprocessableEntityException",
      "message": "Unprocessable Entity Exception",
      "stack":
          UnprocessableEntityException: Unprocessable Entity Exception
              at SessionManagerPlus.waitUntilStatus (/app/dist/core/abc/manager.abc.js:65:19)
              at runNextTicks (node:internal/process/task_queues:65:5)
              at process.processTimers (node:internal/timers:526:9)
              at async ContactsController.checkExists (/app/dist/api/contacts.controller.js:36:26)
      "response": {
        "error": "Session status is not as expected. Try again later or restart the session",
        "session": "session_",
        "status": "STARTING",
        "expected": [
          "WORKING"
        ]
      },
      "status": 422,
      "options": {},
      "name": "UnprocessableEntityException"

**Comment by devlikepro** [comment]
Hi! Could you try to stop all session and start exactly one and send the logs to waha@devlike.pro? That's weird behaviour

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
ANother thing to try is to swithc to chrome based docker image
```
devlikeapro/waha-plus:chrome
```
https://waha.devlike.pro/docs/how-to/engines/#docker-images

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
@whera what is your CPU/Memory configuration? How many sessions do you have? 
Usually timeout happens because it starts all sessions at once when you restart container

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by whera** [comment]
@devlikepro In response to your question, I have three containers running on AWS with the r6a.4xlarge instance, which provides me with 16 vCPUs and 128 GiB of memory to run 90 sessions per container.

I have disabled the setting that automatically starts sessions when the container restarts. Instead, this process is handled internally based on demand to prevent overload.

However, I am facing an issue again: sessions are not being initialized. Even on a new machine and when creating a session from scratch, the problem persists.

This time, I am using the devlikeapro/waha-plus:chrome image, as recommended by you. Below, I am sharing the logs from my attempts to start a session.

```bash
[01:20:42.527] INFO (SessionManager/1): session:session_01jp6hds0y7yz5nxmjr008t83n - Saving session... {"reqId":839,"session":"session_01jp6hds0y7yz5nxmjr008t83n"}
[01:20:42.530] INFO (SessionManager/1): session:session_01jp6hds0y7yz5nxmjr008t83n - Session saved. {"reqId":839,"session":"session_01jp6hds0y7yz5nxmjr008t83n"}
[01:20:42.530] INFO (SessionManager/1): session:session_01jp6hds0y7yz5nxmjr008t83n - Starting session... {"reqId":839,"session":"session_01jp6hds0y7yz5nxmjr008t83n"}
[01:20:42.531] INFO (MediaManager/1): session:session_01jp6hds0y7yz5nxmjr008t83n - Only 'mimetype/ignore-all-media' mimetypes will be downloaded for the session {"reqId":839,"session":"session_01jp6hds0y7yz5nxmjr008t83n"}
[01:20:42.531] INFO (WhatsappSession/1): session:session_01jp6hds0y7yz5nxmjr008t83n - Using cache type: 'local' {"reqId":839,"session":"session_01jp6hds0y7yz5nxmjr008t83n"}
[01:20:42.531] INFO (WhatsappSession/1): session:session_01jp6hds0y7yz5nxmjr008t83n - Using web version: '2.3000.1018072227-alpha' {"reqId":839,"session":"session_01jp6hds0y7yz5nxmjr008t83n"}
[01:20:42.531] INFO (1): session:session_01jp6hds0y7yz5nxmjr008t83n - Session has been started. {"reqId":839,"session":"session_01jp6hds0y7yz5nxmjr008t83n"}
[01:20:42.532] WARN (SessionManager/1): session:session_01jp6hds0y7yz5nxmjr008t83n - Error while getting engine info {"reqId":839,"session":"session_01jp6hds0y7yz5nxmjr008t83n"}
    error: "TypeError: Cannot read properties of null (reading 'evaluate')"
[01:20:42.532] INFO (1): request completed {"reqId":839,"req":{"id":839,"method":"POST","url":"/api/sessions/","query":{},"params":{"0":"api/sessions/"}},"res":{"statusCode":201},"responseTime":6}
[01:20:43.926] INFO (1): request completed {"reqId":840,"req":{"id":840,"method":"GET","url":"/api/version","query":{},"params":{"0":"api/version"}},"res":{"statusCode":304},"responseTime":0}
[01:20:43.977] INFO (1): request completed {"reqId":841,"req":{"id":841,"method":"GET","url":"/api/sessions?all=true","query":{"all":"true"},"params":{"0":"api/sessions"}},"res":{"statusCode":200},"responseTime":2}
[01:20:44.236] INFO (1): request completed {"reqId":842,"req":{"id":842,"method":"GET","url":"/api/server/status","query":{},"params":{"0":"api/server/status"}},"res":{"statusCode":200},"responseTime":1}
[01:23:44.302] ERROR (WhatsappSession/1): session:session_01jp6hds0y7yz5nxmjr008t83n - Runtime.callFunctionOn timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed. {"reqId":839,"session":"session_01jp6hds0y7yz5nxmjr008t83n"}
    err: {
      "type": "ProtocolError",
      "message": "Runtime.callFunctionOn timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.",
      "stack":
          ProtocolError: Runtime.callFunctionOn timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
              at <instance_members_initializer> (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:94:14)
              at new Callback (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:98:16)
              at CallbackRegistry.create (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:23:26)
              at Connection._rawSend (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:90:26)
              at CdpCDPSession.send (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/CDPSession.js:66:33)
              at #evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:360:50)
              at ExecutionContext.evaluateHandle (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:327:36)
              at IsolatedWorld.evaluateHandle (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/IsolatedWorld.js:89:30)
              at CdpJSHandle.evaluateHandle (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/api/JSHandle.js:152:37)
              at WaitTask.rerun (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:103:47)
      "name": "ProtocolError"
    }
[01:23:44.303] INFO (WhatsappSession/1): session:session_01jp6hds0y7yz5nxmjr008t83n - Job scheduled with timeout 2000 ms {"reqId":839,"session":"session_01jp6hds0y7yz5nxmjr008t83n","job":"start-engine","class":"SingleDelayedJobRunner"}
[01:23:46.306] INFO (WhatsappSession/1): session:session_01jp6hds0y7yz5nxmjr008t83n - Using cache type: 'local' {"reqId":839,"session":"session_01jp6hds0y7yz5nxmjr008t83n"}
[01:23:46.306] INFO (WhatsappSession/1): session:session_01jp6hds0y7yz5nxmjr008t83n - Using web version: '2.3000.1018072227-alpha' {"reqId":839,"session":"session_01jp6hds0y7yz5nxmjr008t83n"}
```

Additionally, when I try to take a screenshot, this is what appears:

![Image](https://github.com/user-attachments/assets/7b0e7b7c-7043-421a-9018-cb0218fd7bc0)

**Comment by devlikepro** [comment]
Hi! What WAHA version do you use?
Try removing `WAHA_WEBJS_WEB_VERSION` and `WAHA_WEBJS_CACHE_TYPE` env variables if you're using any

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
> 16 vCPUs and 128 GiB of memory to run 90 sessions per container.

You should not do this :) 
Consider running 9 smaller WAHA instances with 10 sessions each instead, we never tested WEBJS with such number of sessions, can not guaranties that it'll work perfect (with 10 we tested, it worked fine)

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
actually with 50 WEBJS sessions in WAHA as extreme we tested, worked too, but we don't use this pattern in production. Usually it's smaller container with 10 sessions (for WEBJS engine)

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by whera** [comment]
OK, I will follow your recommendation and adjust the containers to 10 sessions each. Could you please recommend an appropriate container size (CPU/MEM) to run these 10 sessions?

Also, I would like to inform you that the issue was resolved when we disabled the cache.

**Comment by devlikepro** [comment]
https://waha.devlike.pro/docs/overview/faq/#how-much-cpu-and-memory-does-waha-need

But it depends a lot on the accounts/payload/history, so you need to adjust it for your use case.

Awesome, closing the issue!

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by vilsonnjr** [comment]
> Hi! What WAHA version do you use? Try removing `WAHA_WEBJS_WEB_VERSION` and `WAHA_WEBJS_CACHE_TYPE` env variables if you're using any
> 
> [![patron:PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

I’m having the same issue when using cache — the sessions don’t start. Why does this happen? I wanted to use cache because my proxy is consuming too much bandwidth.

I'm using version 2025.7.6.

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
