### ISSUE TITLE
Error 500 sending images

### ISSUE THREAD

**Issue by andrearuffini** [allburov/whatsapp-http-api#76]
Hi
I am trying to send images but I get an error 500. 
It worked fine for a while and now I suddenly got this error.
Text-only messages are working well.

I have installed the latest version of WAHA plus.

This is my API call body:
```javascript
{
  "session": "sessionName",
  "chatId": "391111010101@c.us",
  "file": {
    "mimetype": "image/jpeg",
    "url": "https://www.example.it/Thumbnail.jpg",
    "filename": "Thumbnail.jpg"
  },
  "caption": "This is the caption text..."
}
``` 

And this is the answer:
```javascript
{
  "statusCode": 500,
  "timestamp": "2023-03-20T15:51:12.879Z",
  "exception": {
    "stack": "Error: Evaluation failed: TypeError: window.Store.MediaPrep.prepRawMedia is not a function\n    at window.WWebJS.processMediaData (__puppeteer_evaluation_script__:235:50)\n    at async window.WWebJS.sendMessage (__puppeteer_evaluation_script__:19:19)\n    at async __puppeteer_evaluation_script__:10:25\n    at ExecutionContext._evaluateInternal (/app/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ExecutionContext.evaluate (/app/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)\n    at async Client.sendMessage (/app/node_modules/whatsapp-web.js/src/Client.js:686:28)\n    at async /app/node_modules/@nestjs/core/router/router-execution-context.js:46:28\n    at async /app/node_modules/@nestjs/core/router/router-proxy.js:9:17",
    "message": "Evaluation failed: TypeError: window.Store.MediaPrep.prepRawMedia is not a function\n    at window.WWebJS.processMediaData (__puppeteer_evaluation_script__:235:50)\n    at async window.WWebJS.sendMessage (__puppeteer_evaluation_script__:19:19)\n    at async __puppeteer_evaluation_script__:10:25",
    "name": "Error"
  },
  "request": {
    "path": "/api/sendImage",
    "method": "POST",
    "body": {
      "session": "sessionName",
      "chatId": "391111010101@c.us",
      "file": {
        "mimetype": "image/jpeg",
        "url": "https://www.example.it/Thumbnail.jpg",
        "filename": "Thumbnail.jpg"
      },
      "caption": "This is the caption text..."
    },
    "query": {}
  },
  "version": {
    "version": "2023.3.1",
    "tier": "PLUS",
    "browser": "/usr/bin/chromium"
  }
}
``` 

Thanks for your help

**Comment by allburov** [comment]
Hi! Fixed in the latest version today, `2023.3.22`, please pull it and try again!
