### ISSUE TITLE
Throwing error when sendImage

### ISSUE THREAD

**Issue by arthurbarros** [allburov/whatsapp-http-api#78]
```
curl -X 'POST' \
  'http://**********/api/sendImage' \
  -H 'accept: application/json' \
  -H 'X-Api-Key: **********' \
  -H 'Content-Type: application/json' \
  -d '{
  "chatId": "**********@c.us",
  "file": {
    "mimetype": "image/jpeg",
    "url": "https://github.com/devlikeapro/whatsapp-http-api/raw/core/examples/dev.likeapro.jpg",
    "filename": "filename.jpeg"
  },
  "caption": "Hello World",
  "session": "default"
}'
```

It was working fine a couple days ago, but know when I try to use the same endpoint a error is thrown, as shown bellow:

```
{
  "statusCode": 500,
  "timestamp": "2023-03-23T17:29:57.708Z",
  "exception": {
    "stack": "Error: Evaluation failed: TypeError: window.Store.MediaPrep.prepRawMedia is not a function\n    at window.WWebJS.processMediaData (__puppeteer_evaluation_script__:235:50)\n    at async window.WWebJS.sendMessage (__puppeteer_evaluation_script__:19:19)\n    at async __puppeteer_evaluation_script__:10:25\n    at ExecutionContext._evaluateInternal (/app/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ExecutionContext.evaluate (/app/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)\n    at async Client.sendMessage (/app/node_modules/whatsapp-web.js/src/Client.js:686:28)\n    at async /app/node_modules/@nestjs/core/router/router-execution-context.js:46:28\n    at async /app/node_modules/@nestjs/core/router/router-proxy.js:9:17",
    "message": "Evaluation failed: TypeError: window.Store.MediaPrep.prepRawMedia is not a function\n    at window.WWebJS.processMediaData (__puppeteer_evaluation_script__:235:50)\n    at async window.WWebJS.sendMessage (__puppeteer_evaluation_script__:19:19)\n    at async __puppeteer_evaluation_script__:10:25",
    "name": "Error"
  },
  "request": {
    "path": "/api/sendImage",
    "method": "POST",
    "body": {
      "chatId": "**********@c.us",
      "file": {
        "mimetype": "image/jpeg",
        "url": "https://github.com/devlikeapro/whatsapp-http-api/raw/core/examples/dev.likeapro.jpg",
        "filename": "filename.jpeg"
      },
      "caption": "Hello World",
      "session": "default"
    },
    "query": {}
  },
  "version": {
    "version": "2023.3.1",
    "tier": "PLUS",
    "browser": "/usr/bin/chromium"
  }
}
```

I was looking up the error on WWebJs and apparently there is a Merged PR about 4 days ago.
https://github.com/pedroslopez/whatsapp-web.js/pull/2074

**Comment by arthurbarros** [comment]
I'm using the PLUS version (supporter on Patreon)

This is the diggest from the latest version that I pulled from the private repo:

 ```
 $ docker pull devlikeapro/whatsapp-http-api-plus
Using default tag: latest
latest: Pulling from devlikeapro/whatsapp-http-api-plus
Digest: sha256:1588219f83da739d82d3692ce0f79985baeea389d8071c15e5aae4c76f4f8347
Status: Image is up to date for devlikeapro/whatsapp-http-api-plus:latest
docker.io/devlikeapro/whatsapp-http-api-plus:latest

```

**Comment by allburov** [comment]
Hi! 
Please pull the new image - it has been fixed in https://github.com/devlikeapro/whatsapp-http-api/issues/76
I've tried the request `POST /api/sendImage/` - it worked on the latest version
```json
{
  "chatId": "79111@c.us",
  "file": {
    "mimetype": "image/jpeg",
    "filename": "filename.jpeg",
    "url": "https://github.com/devlikeapro/whatsapp-http-api/raw/core/examples/dev.likeapro.jpg"
  },
  "caption": "string",
  "session": "default"
}
```

Btw, you have to stop and start container again after you pull new image - I see in logs `2023.3.1"` version, but the latest one is `2023.3.21`
