### ISSUE TITLE
[PLUS] Session getting closed right after scanning the QR Code

### ISSUE THREAD

**Issue by arthurbarros** [allburov/whatsapp-http-api#85]
I'm facing a issue with one session, right after scanning the QR Code.

And when I try to take a screenshot, this shows up.
There are other 3 sessions that are working fine.

```
{
  "statusCode": 500,
  "timestamp": "2023-04-15T13:50:45.616Z",
  "exception": {
    "stack": "Error: Protocol error (Target.activateTarget): Session closed. Most likely the page has been closed.\n    at CDPSession.send (/app/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:218:35)\n    at Page._screenshotTask (/app/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1984:28)\n    at /app/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1981:62",
    "message": "Protocol error (Target.activateTarget): Session closed. Most likely the page has been closed.",
    "name": "Error"
  },
  "request": {
    "path": "/api/screenshot?session=adbd7d97-7758-4cd3-a529-5ce90d233a76",
    "method": "GET",
    "body": {},
    "query": {
      "session": "adbd7d97-7758-4cd3-a529-5ce90d233a76"
    }
  },
  "version": {
    "version": "2023.3.21",
    "tier": "PLUS",
    "browser": "/usr/bin/chromium"
  }
}
```

**Comment by allburov** [comment]
Hi!
Is there RAM available on the server? I saw it few times when there was no free memory

**Comment by arthurbarros** [comment]
```
~ $ free -m
              total        used        free      shared  buff/cache   available
Mem:           3928        1171        2104           0         653        2529
Swap:             0           0           0
```

Over 2GB of free RAM on the server

**Comment by arthurbarros** [comment]
@devlikeapro any ideas ?

**Comment by allburov** [comment]
@arthurbarros hi! I didn't manage to reproduce it locally.

Does it work after restart? Is it reproducible on other machine?

Just need to understand what causes it - either because of long running container or it's internal bug.

**Comment by arthurbarros** [comment]
@allburov The issue didn't appear again. But can't tell exaclty what happened. the only thing I've done so far was removing all the session folder and start it again.

I think we can close this bug for now. If the issue surface again I open another one with more details
